// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: config/route/v1/route_components.proto

package routev1

import (
	v1 "github.com/dubbo-kubernetes/xds-api/type/matcher/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [#next-free-field: 26]
type VirtualHost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domains       []string               `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	Routes        []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualHost) Reset() {
	*x = VirtualHost{}
	mi := &file_config_route_v1_route_components_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualHost) ProtoMessage() {}

func (x *VirtualHost) ProtoReflect() protoreflect.Message {
	mi := &file_config_route_v1_route_components_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualHost.ProtoReflect.Descriptor instead.
func (*VirtualHost) Descriptor() ([]byte, []int) {
	return file_config_route_v1_route_components_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualHost) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualHost) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *VirtualHost) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Match *RouteMatch            `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*Route_Route
	Action        isRoute_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_config_route_v1_route_components_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_config_route_v1_route_components_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_config_route_v1_route_components_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetMatch() *RouteMatch {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *Route) GetAction() isRoute_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Route) GetRoute() *RouteAction {
	if x != nil {
		if x, ok := x.Action.(*Route_Route); ok {
			return x.Route
		}
	}
	return nil
}

type isRoute_Action interface {
	isRoute_Action()
}

type Route_Route struct {
	Route *RouteAction `protobuf:"bytes,3,opt,name=route,proto3,oneof"`
}

func (*Route_Route) isRoute_Action() {}

type WeightedCluster struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Clusters      []*WeightedCluster_ClusterWeight `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	TotalWeight   *wrapperspb.UInt32Value          `protobuf:"bytes,2,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightedCluster) Reset() {
	*x = WeightedCluster{}
	mi := &file_config_route_v1_route_components_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightedCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedCluster) ProtoMessage() {}

func (x *WeightedCluster) ProtoReflect() protoreflect.Message {
	mi := &file_config_route_v1_route_components_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedCluster.ProtoReflect.Descriptor instead.
func (*WeightedCluster) Descriptor() ([]byte, []int) {
	return file_config_route_v1_route_components_proto_rawDescGZIP(), []int{2}
}

func (x *WeightedCluster) GetClusters() []*WeightedCluster_ClusterWeight {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *WeightedCluster) GetTotalWeight() *wrapperspb.UInt32Value {
	if x != nil {
		return x.TotalWeight
	}
	return nil
}

// [#next-free-field: 18]
type RouteMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PathSpecifier:
	//
	//	*RouteMatch_Prefix
	//	*RouteMatch_Path
	//	*RouteMatch_SafeRegex
	PathSpecifier isRouteMatch_PathSpecifier `protobuf_oneof:"path_specifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMatch) Reset() {
	*x = RouteMatch{}
	mi := &file_config_route_v1_route_components_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMatch) ProtoMessage() {}

func (x *RouteMatch) ProtoReflect() protoreflect.Message {
	mi := &file_config_route_v1_route_components_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMatch.ProtoReflect.Descriptor instead.
func (*RouteMatch) Descriptor() ([]byte, []int) {
	return file_config_route_v1_route_components_proto_rawDescGZIP(), []int{3}
}

func (x *RouteMatch) GetPathSpecifier() isRouteMatch_PathSpecifier {
	if x != nil {
		return x.PathSpecifier
	}
	return nil
}

func (x *RouteMatch) GetPrefix() string {
	if x != nil {
		if x, ok := x.PathSpecifier.(*RouteMatch_Prefix); ok {
			return x.Prefix
		}
	}
	return ""
}

func (x *RouteMatch) GetPath() string {
	if x != nil {
		if x, ok := x.PathSpecifier.(*RouteMatch_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *RouteMatch) GetSafeRegex() *v1.RegexMatcher {
	if x != nil {
		if x, ok := x.PathSpecifier.(*RouteMatch_SafeRegex); ok {
			return x.SafeRegex
		}
	}
	return nil
}

type isRouteMatch_PathSpecifier interface {
	isRouteMatch_PathSpecifier()
}

type RouteMatch_Prefix struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3,oneof"`
}

type RouteMatch_Path struct {
	Path string `protobuf:"bytes,2,opt,name=path,proto3,oneof"`
}

type RouteMatch_SafeRegex struct {
	SafeRegex *v1.RegexMatcher `protobuf:"bytes,10,opt,name=safe_regex,json=safeRegex,proto3,oneof"`
}

func (*RouteMatch_Prefix) isRouteMatch_PathSpecifier() {}

func (*RouteMatch_Path) isRouteMatch_PathSpecifier() {}

func (*RouteMatch_SafeRegex) isRouteMatch_PathSpecifier() {}

// [#next-free-field: 42]
type RouteAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ClusterSpecifier:
	//
	//	*RouteAction_Cluster
	//	*RouteAction_WeightedClusters
	ClusterSpecifier isRouteAction_ClusterSpecifier `protobuf_oneof:"cluster_specifier"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteAction) Reset() {
	*x = RouteAction{}
	mi := &file_config_route_v1_route_components_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAction) ProtoMessage() {}

func (x *RouteAction) ProtoReflect() protoreflect.Message {
	mi := &file_config_route_v1_route_components_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAction.ProtoReflect.Descriptor instead.
func (*RouteAction) Descriptor() ([]byte, []int) {
	return file_config_route_v1_route_components_proto_rawDescGZIP(), []int{4}
}

func (x *RouteAction) GetClusterSpecifier() isRouteAction_ClusterSpecifier {
	if x != nil {
		return x.ClusterSpecifier
	}
	return nil
}

func (x *RouteAction) GetCluster() string {
	if x != nil {
		if x, ok := x.ClusterSpecifier.(*RouteAction_Cluster); ok {
			return x.Cluster
		}
	}
	return ""
}

func (x *RouteAction) GetWeightedClusters() *WeightedCluster {
	if x != nil {
		if x, ok := x.ClusterSpecifier.(*RouteAction_WeightedClusters); ok {
			return x.WeightedClusters
		}
	}
	return nil
}

type isRouteAction_ClusterSpecifier interface {
	isRouteAction_ClusterSpecifier()
}

type RouteAction_Cluster struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3,oneof"`
}

type RouteAction_WeightedClusters struct {
	WeightedClusters *WeightedCluster `protobuf:"bytes,3,opt,name=weighted_clusters,json=weightedClusters,proto3,oneof"`
}

func (*RouteAction_Cluster) isRouteAction_ClusterSpecifier() {}

func (*RouteAction_WeightedClusters) isRouteAction_ClusterSpecifier() {}

type WeightedCluster_ClusterWeight struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight        *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=weight,proto3" json:"weight,omitempty"`
	ClusterHeader string                  `protobuf:"bytes,12,opt,name=cluster_header,json=clusterHeader,proto3" json:"cluster_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightedCluster_ClusterWeight) Reset() {
	*x = WeightedCluster_ClusterWeight{}
	mi := &file_config_route_v1_route_components_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightedCluster_ClusterWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedCluster_ClusterWeight) ProtoMessage() {}

func (x *WeightedCluster_ClusterWeight) ProtoReflect() protoreflect.Message {
	mi := &file_config_route_v1_route_components_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedCluster_ClusterWeight.ProtoReflect.Descriptor instead.
func (*WeightedCluster_ClusterWeight) Descriptor() ([]byte, []int) {
	return file_config_route_v1_route_components_proto_rawDescGZIP(), []int{2, 0}
}

func (x *WeightedCluster_ClusterWeight) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WeightedCluster_ClusterWeight) GetWeight() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *WeightedCluster_ClusterWeight) GetClusterHeader() string {
	if x != nil {
		return x.ClusterHeader
	}
	return ""
}

var File_config_route_v1_route_components_proto protoreflect.FileDescriptor

const file_config_route_v1_route_components_proto_rawDesc = "" +
	"\n" +
	"&config/route/v1/route_components.proto\x12\x0fconfig.route.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1btype/matcher/v1/regex.proto\"k\n" +
	"\vVirtualHost\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adomains\x18\x02 \x03(\tR\adomains\x12.\n" +
	"\x06routes\x18\x03 \x03(\v2\x16.config.route.v1.RouteR\x06routes\"\x8e\x01\n" +
	"\x05Route\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x05match\x18\x02 \x01(\v2\x1b.config.route.v1.RouteMatchR\x05match\x124\n" +
	"\x05route\x18\x03 \x01(\v2\x1c.config.route.v1.RouteActionH\x00R\x05routeB\b\n" +
	"\x06action\"\xa1\x02\n" +
	"\x0fWeightedCluster\x12J\n" +
	"\bclusters\x18\x01 \x03(\v2..config.route.v1.WeightedCluster.ClusterWeightR\bclusters\x12?\n" +
	"\ftotal_weight\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\vtotalWeight\x1a\x80\x01\n" +
	"\rClusterWeight\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x06weight\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x06weight\x12%\n" +
	"\x0ecluster_header\x18\f \x01(\tR\rclusterHeader\"\x8e\x01\n" +
	"\n" +
	"RouteMatch\x12\x18\n" +
	"\x06prefix\x18\x01 \x01(\tH\x00R\x06prefix\x12\x14\n" +
	"\x04path\x18\x02 \x01(\tH\x00R\x04path\x12>\n" +
	"\n" +
	"safe_regex\x18\n" +
	" \x01(\v2\x1d.type.matcher.v1.RegexMatcherH\x00R\tsafeRegexB\x10\n" +
	"\x0epath_specifier\"\x8f\x01\n" +
	"\vRouteAction\x12\x1a\n" +
	"\acluster\x18\x01 \x01(\tH\x00R\acluster\x12O\n" +
	"\x11weighted_clusters\x18\x03 \x01(\v2 .config.route.v1.WeightedClusterH\x00R\x10weightedClustersB\x13\n" +
	"\x11cluster_specifierB=Z;github.com/dubbo-kubernetes/xds-api/config/route/v1;routev1b\x06proto3"

var (
	file_config_route_v1_route_components_proto_rawDescOnce sync.Once
	file_config_route_v1_route_components_proto_rawDescData []byte
)

func file_config_route_v1_route_components_proto_rawDescGZIP() []byte {
	file_config_route_v1_route_components_proto_rawDescOnce.Do(func() {
		file_config_route_v1_route_components_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_route_v1_route_components_proto_rawDesc), len(file_config_route_v1_route_components_proto_rawDesc)))
	})
	return file_config_route_v1_route_components_proto_rawDescData
}

var file_config_route_v1_route_components_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_config_route_v1_route_components_proto_goTypes = []any{
	(*VirtualHost)(nil),                   // 0: config.route.v1.VirtualHost
	(*Route)(nil),                         // 1: config.route.v1.Route
	(*WeightedCluster)(nil),               // 2: config.route.v1.WeightedCluster
	(*RouteMatch)(nil),                    // 3: config.route.v1.RouteMatch
	(*RouteAction)(nil),                   // 4: config.route.v1.RouteAction
	(*WeightedCluster_ClusterWeight)(nil), // 5: config.route.v1.WeightedCluster.ClusterWeight
	(*wrapperspb.UInt32Value)(nil),        // 6: google.protobuf.UInt32Value
	(*v1.RegexMatcher)(nil),               // 7: type.matcher.v1.RegexMatcher
}
var file_config_route_v1_route_components_proto_depIdxs = []int32{
	1, // 0: config.route.v1.VirtualHost.routes:type_name -> config.route.v1.Route
	3, // 1: config.route.v1.Route.match:type_name -> config.route.v1.RouteMatch
	4, // 2: config.route.v1.Route.route:type_name -> config.route.v1.RouteAction
	5, // 3: config.route.v1.WeightedCluster.clusters:type_name -> config.route.v1.WeightedCluster.ClusterWeight
	6, // 4: config.route.v1.WeightedCluster.total_weight:type_name -> google.protobuf.UInt32Value
	7, // 5: config.route.v1.RouteMatch.safe_regex:type_name -> type.matcher.v1.RegexMatcher
	2, // 6: config.route.v1.RouteAction.weighted_clusters:type_name -> config.route.v1.WeightedCluster
	6, // 7: config.route.v1.WeightedCluster.ClusterWeight.weight:type_name -> google.protobuf.UInt32Value
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_config_route_v1_route_components_proto_init() }
func file_config_route_v1_route_components_proto_init() {
	if File_config_route_v1_route_components_proto != nil {
		return
	}
	file_config_route_v1_route_components_proto_msgTypes[1].OneofWrappers = []any{
		(*Route_Route)(nil),
	}
	file_config_route_v1_route_components_proto_msgTypes[3].OneofWrappers = []any{
		(*RouteMatch_Prefix)(nil),
		(*RouteMatch_Path)(nil),
		(*RouteMatch_SafeRegex)(nil),
	}
	file_config_route_v1_route_components_proto_msgTypes[4].OneofWrappers = []any{
		(*RouteAction_Cluster)(nil),
		(*RouteAction_WeightedClusters)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_route_v1_route_components_proto_rawDesc), len(file_config_route_v1_route_components_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_route_v1_route_components_proto_goTypes,
		DependencyIndexes: file_config_route_v1_route_components_proto_depIdxs,
		MessageInfos:      file_config_route_v1_route_components_proto_msgTypes,
	}.Build()
	File_config_route_v1_route_components_proto = out.File
	file_config_route_v1_route_components_proto_goTypes = nil
	file_config_route_v1_route_components_proto_depIdxs = nil
}
