// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: listener/v1/listener_components.proto

package listenerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ConfigType:
	//
	//	*Filter_TypedConfig
	ConfigType    isFilter_ConfigType `protobuf_oneof:"config_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_listener_v1_listener_components_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_listener_v1_listener_components_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_listener_v1_listener_components_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Filter) GetConfigType() isFilter_ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return nil
}

func (x *Filter) GetTypedConfig() *anypb.Any {
	if x != nil {
		if x, ok := x.ConfigType.(*Filter_TypedConfig); ok {
			return x.TypedConfig
		}
	}
	return nil
}

type isFilter_ConfigType interface {
	isFilter_ConfigType()
}

type Filter_TypedConfig struct {
	TypedConfig *anypb.Any `protobuf:"bytes,4,opt,name=typed_config,json=typedConfig,proto3,oneof"`
}

func (*Filter_TypedConfig) isFilter_ConfigType() {}

// [#next-free-field: 10]
type FilterChain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterChain) Reset() {
	*x = FilterChain{}
	mi := &file_listener_v1_listener_components_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterChain) ProtoMessage() {}

func (x *FilterChain) ProtoReflect() protoreflect.Message {
	mi := &file_listener_v1_listener_components_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterChain.ProtoReflect.Descriptor instead.
func (*FilterChain) Descriptor() ([]byte, []int) {
	return file_listener_v1_listener_components_proto_rawDescGZIP(), []int{1}
}

func (x *FilterChain) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

var File_listener_v1_listener_components_proto protoreflect.FileDescriptor

const file_listener_v1_listener_components_proto_rawDesc = "" +
	"\n" +
	"%listener/v1/listener_components.proto\x12\vlistener.v1\x1a\x19google/protobuf/any.proto\"z\n" +
	"\x06Filter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\ftyped_config\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\vtypedConfigB\r\n" +
	"\vconfig_typeJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x06config\"n\n" +
	"\vFilterChain\x12-\n" +
	"\afilters\x18\x03 \x03(\v2\x13.listener.v1.FilterR\afiltersJ\x04\b\x02\x10\x03J\x04\b\b\x10\tR\vtls_contextR\x17on_demand_configurationB<Z:github.com/dubbo-kubernetes/xds-api/listener/v1;listenerv1b\x06proto3"

var (
	file_listener_v1_listener_components_proto_rawDescOnce sync.Once
	file_listener_v1_listener_components_proto_rawDescData []byte
)

func file_listener_v1_listener_components_proto_rawDescGZIP() []byte {
	file_listener_v1_listener_components_proto_rawDescOnce.Do(func() {
		file_listener_v1_listener_components_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listener_v1_listener_components_proto_rawDesc), len(file_listener_v1_listener_components_proto_rawDesc)))
	})
	return file_listener_v1_listener_components_proto_rawDescData
}

var file_listener_v1_listener_components_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_listener_v1_listener_components_proto_goTypes = []any{
	(*Filter)(nil),      // 0: listener.v1.Filter
	(*FilterChain)(nil), // 1: listener.v1.FilterChain
	(*anypb.Any)(nil),   // 2: google.protobuf.Any
}
var file_listener_v1_listener_components_proto_depIdxs = []int32{
	2, // 0: listener.v1.Filter.typed_config:type_name -> google.protobuf.Any
	0, // 1: listener.v1.FilterChain.filters:type_name -> listener.v1.Filter
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_listener_v1_listener_components_proto_init() }
func file_listener_v1_listener_components_proto_init() {
	if File_listener_v1_listener_components_proto != nil {
		return
	}
	file_listener_v1_listener_components_proto_msgTypes[0].OneofWrappers = []any{
		(*Filter_TypedConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listener_v1_listener_components_proto_rawDesc), len(file_listener_v1_listener_components_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listener_v1_listener_components_proto_goTypes,
		DependencyIndexes: file_listener_v1_listener_components_proto_depIdxs,
		MessageInfos:      file_listener_v1_listener_components_proto_msgTypes,
	}.Build()
	File_listener_v1_listener_components_proto = out.File
	file_listener_v1_listener_components_proto_goTypes = nil
	file_listener_v1_listener_components_proto_depIdxs = nil
}
