// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: extensions/transport_sockets/tls/v1/tls.proto

package tlsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpstreamTlsContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommonTlsContext *CommonTlsContext      `protobuf:"bytes,1,opt,name=common_tls_context,json=commonTlsContext,proto3" json:"common_tls_context,omitempty"`
	Sni              string                 `protobuf:"bytes,2,opt,name=sni,proto3" json:"sni,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpstreamTlsContext) Reset() {
	*x = UpstreamTlsContext{}
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamTlsContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamTlsContext) ProtoMessage() {}

func (x *UpstreamTlsContext) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamTlsContext.ProtoReflect.Descriptor instead.
func (*UpstreamTlsContext) Descriptor() ([]byte, []int) {
	return file_extensions_transport_sockets_tls_v1_tls_proto_rawDescGZIP(), []int{0}
}

func (x *UpstreamTlsContext) GetCommonTlsContext() *CommonTlsContext {
	if x != nil {
		return x.CommonTlsContext
	}
	return nil
}

func (x *UpstreamTlsContext) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

type DownstreamTlsContext struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CommonTlsContext         *CommonTlsContext      `protobuf:"bytes,1,opt,name=common_tls_context,json=commonTlsContext,proto3" json:"common_tls_context,omitempty"`
	RequireClientCertificate *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=require_client_certificate,json=requireClientCertificate,proto3" json:"require_client_certificate,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DownstreamTlsContext) Reset() {
	*x = DownstreamTlsContext{}
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownstreamTlsContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownstreamTlsContext) ProtoMessage() {}

func (x *DownstreamTlsContext) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownstreamTlsContext.ProtoReflect.Descriptor instead.
func (*DownstreamTlsContext) Descriptor() ([]byte, []int) {
	return file_extensions_transport_sockets_tls_v1_tls_proto_rawDescGZIP(), []int{1}
}

func (x *DownstreamTlsContext) GetCommonTlsContext() *CommonTlsContext {
	if x != nil {
		return x.CommonTlsContext
	}
	return nil
}

func (x *DownstreamTlsContext) GetRequireClientCertificate() *wrapperspb.BoolValue {
	if x != nil {
		return x.RequireClientCertificate
	}
	return nil
}

type CommonTlsContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ValidationContextType:
	//
	//	*CommonTlsContext_CombinedValidationContext
	ValidationContextType isCommonTlsContext_ValidationContextType `protobuf_oneof:"validation_context_type"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CommonTlsContext) Reset() {
	*x = CommonTlsContext{}
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonTlsContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonTlsContext) ProtoMessage() {}

func (x *CommonTlsContext) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonTlsContext.ProtoReflect.Descriptor instead.
func (*CommonTlsContext) Descriptor() ([]byte, []int) {
	return file_extensions_transport_sockets_tls_v1_tls_proto_rawDescGZIP(), []int{2}
}

func (x *CommonTlsContext) GetValidationContextType() isCommonTlsContext_ValidationContextType {
	if x != nil {
		return x.ValidationContextType
	}
	return nil
}

func (x *CommonTlsContext) GetCombinedValidationContext() *CommonTlsContext_CombinedCertificateValidationContext {
	if x != nil {
		if x, ok := x.ValidationContextType.(*CommonTlsContext_CombinedValidationContext); ok {
			return x.CombinedValidationContext
		}
	}
	return nil
}

type isCommonTlsContext_ValidationContextType interface {
	isCommonTlsContext_ValidationContextType()
}

type CommonTlsContext_CombinedValidationContext struct {
	CombinedValidationContext *CommonTlsContext_CombinedCertificateValidationContext `protobuf:"bytes,8,opt,name=combined_validation_context,json=combinedValidationContext,proto3,oneof"`
}

func (*CommonTlsContext_CombinedValidationContext) isCommonTlsContext_ValidationContextType() {}

type CommonTlsContext_CertificateProviderInstance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstanceName    string                 `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	CertificateName string                 `protobuf:"bytes,2,opt,name=certificate_name,json=certificateName,proto3" json:"certificate_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommonTlsContext_CertificateProviderInstance) Reset() {
	*x = CommonTlsContext_CertificateProviderInstance{}
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonTlsContext_CertificateProviderInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonTlsContext_CertificateProviderInstance) ProtoMessage() {}

func (x *CommonTlsContext_CertificateProviderInstance) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonTlsContext_CertificateProviderInstance.ProtoReflect.Descriptor instead.
func (*CommonTlsContext_CertificateProviderInstance) Descriptor() ([]byte, []int) {
	return file_extensions_transport_sockets_tls_v1_tls_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CommonTlsContext_CertificateProviderInstance) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *CommonTlsContext_CertificateProviderInstance) GetCertificateName() string {
	if x != nil {
		return x.CertificateName
	}
	return ""
}

type CommonTlsContext_CombinedCertificateValidationContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonTlsContext_CombinedCertificateValidationContext) Reset() {
	*x = CommonTlsContext_CombinedCertificateValidationContext{}
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonTlsContext_CombinedCertificateValidationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonTlsContext_CombinedCertificateValidationContext) ProtoMessage() {}

func (x *CommonTlsContext_CombinedCertificateValidationContext) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonTlsContext_CombinedCertificateValidationContext.ProtoReflect.Descriptor instead.
func (*CommonTlsContext_CombinedCertificateValidationContext) Descriptor() ([]byte, []int) {
	return file_extensions_transport_sockets_tls_v1_tls_proto_rawDescGZIP(), []int{2, 1}
}

var File_extensions_transport_sockets_tls_v1_tls_proto protoreflect.FileDescriptor

const file_extensions_transport_sockets_tls_v1_tls_proto_rawDesc = "" +
	"\n" +
	"-extensions/transport_sockets/tls/v1/tls.proto\x12#extensions.transport_sockets.tls.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\x8b\x01\n" +
	"\x12UpstreamTlsContext\x12c\n" +
	"\x12common_tls_context\x18\x01 \x01(\v25.extensions.transport_sockets.tls.v1.CommonTlsContextR\x10commonTlsContext\x12\x10\n" +
	"\x03sni\x18\x02 \x01(\tR\x03sni\"\xd5\x01\n" +
	"\x14DownstreamTlsContext\x12c\n" +
	"\x12common_tls_context\x18\x01 \x01(\v25.extensions.transport_sockets.tls.v1.CommonTlsContextR\x10commonTlsContext\x12X\n" +
	"\x1arequire_client_certificate\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\x18requireClientCertificate\"\xe9\x02\n" +
	"\x10CommonTlsContext\x12\x9c\x01\n" +
	"\x1bcombined_validation_context\x18\b \x01(\v2Z.extensions.transport_sockets.tls.v1.CommonTlsContext.CombinedCertificateValidationContextH\x00R\x19combinedValidationContext\x1am\n" +
	"\x1bCertificateProviderInstance\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12)\n" +
	"\x10certificate_name\x18\x02 \x01(\tR\x0fcertificateName\x1a&\n" +
	"$CombinedCertificateValidationContextB\x19\n" +
	"\x17validation_context_typeJ\x04\b\x05\x10\x06BOZMgithub.com/dubbo-kubernetes/xds-api/extensions/transport_sockets/tls/v1;tlsv1b\x06proto3"

var (
	file_extensions_transport_sockets_tls_v1_tls_proto_rawDescOnce sync.Once
	file_extensions_transport_sockets_tls_v1_tls_proto_rawDescData []byte
)

func file_extensions_transport_sockets_tls_v1_tls_proto_rawDescGZIP() []byte {
	file_extensions_transport_sockets_tls_v1_tls_proto_rawDescOnce.Do(func() {
		file_extensions_transport_sockets_tls_v1_tls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_transport_sockets_tls_v1_tls_proto_rawDesc), len(file_extensions_transport_sockets_tls_v1_tls_proto_rawDesc)))
	})
	return file_extensions_transport_sockets_tls_v1_tls_proto_rawDescData
}

var file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_extensions_transport_sockets_tls_v1_tls_proto_goTypes = []any{
	(*UpstreamTlsContext)(nil),                                    // 0: extensions.transport_sockets.tls.v1.UpstreamTlsContext
	(*DownstreamTlsContext)(nil),                                  // 1: extensions.transport_sockets.tls.v1.DownstreamTlsContext
	(*CommonTlsContext)(nil),                                      // 2: extensions.transport_sockets.tls.v1.CommonTlsContext
	(*CommonTlsContext_CertificateProviderInstance)(nil),          // 3: extensions.transport_sockets.tls.v1.CommonTlsContext.CertificateProviderInstance
	(*CommonTlsContext_CombinedCertificateValidationContext)(nil), // 4: extensions.transport_sockets.tls.v1.CommonTlsContext.CombinedCertificateValidationContext
	(*wrapperspb.BoolValue)(nil),                                  // 5: google.protobuf.BoolValue
}
var file_extensions_transport_sockets_tls_v1_tls_proto_depIdxs = []int32{
	2, // 0: extensions.transport_sockets.tls.v1.UpstreamTlsContext.common_tls_context:type_name -> extensions.transport_sockets.tls.v1.CommonTlsContext
	2, // 1: extensions.transport_sockets.tls.v1.DownstreamTlsContext.common_tls_context:type_name -> extensions.transport_sockets.tls.v1.CommonTlsContext
	5, // 2: extensions.transport_sockets.tls.v1.DownstreamTlsContext.require_client_certificate:type_name -> google.protobuf.BoolValue
	4, // 3: extensions.transport_sockets.tls.v1.CommonTlsContext.combined_validation_context:type_name -> extensions.transport_sockets.tls.v1.CommonTlsContext.CombinedCertificateValidationContext
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_extensions_transport_sockets_tls_v1_tls_proto_init() }
func file_extensions_transport_sockets_tls_v1_tls_proto_init() {
	if File_extensions_transport_sockets_tls_v1_tls_proto != nil {
		return
	}
	file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes[2].OneofWrappers = []any{
		(*CommonTlsContext_CombinedValidationContext)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_transport_sockets_tls_v1_tls_proto_rawDesc), len(file_extensions_transport_sockets_tls_v1_tls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_transport_sockets_tls_v1_tls_proto_goTypes,
		DependencyIndexes: file_extensions_transport_sockets_tls_v1_tls_proto_depIdxs,
		MessageInfos:      file_extensions_transport_sockets_tls_v1_tls_proto_msgTypes,
	}.Build()
	File_extensions_transport_sockets_tls_v1_tls_proto = out.File
	file_extensions_transport_sockets_tls_v1_tls_proto_goTypes = nil
	file_extensions_transport_sockets_tls_v1_tls_proto_depIdxs = nil
}
