// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: cluster/v1/cluster.proto

package clusterv1

import (
	v11 "github.com/dubbo-kubernetes/xds-api/core/v1"
	v1 "github.com/dubbo-kubernetes/xds-api/endpoint/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cluster_DiscoveryType int32

const (
	Cluster_STATIC      Cluster_DiscoveryType = 0
	Cluster_STRICT_DNS  Cluster_DiscoveryType = 1
	Cluster_LOGICAL_DNS Cluster_DiscoveryType = 2
	Cluster_EDS         Cluster_DiscoveryType = 3
)

// Enum value maps for Cluster_DiscoveryType.
var (
	Cluster_DiscoveryType_name = map[int32]string{
		0: "STATIC",
		1: "STRICT_DNS",
		2: "LOGICAL_DNS",
		3: "EDS",
	}
	Cluster_DiscoveryType_value = map[string]int32{
		"STATIC":      0,
		"STRICT_DNS":  1,
		"LOGICAL_DNS": 2,
		"EDS":         3,
	}
)

func (x Cluster_DiscoveryType) Enum() *Cluster_DiscoveryType {
	p := new(Cluster_DiscoveryType)
	*p = x
	return p
}

func (x Cluster_DiscoveryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cluster_DiscoveryType) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_v1_cluster_proto_enumTypes[0].Descriptor()
}

func (Cluster_DiscoveryType) Type() protoreflect.EnumType {
	return &file_cluster_v1_cluster_proto_enumTypes[0]
}

func (x Cluster_DiscoveryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cluster_DiscoveryType.Descriptor instead.
func (Cluster_DiscoveryType) EnumDescriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0, 0}
}

type Cluster_LbPolicy int32

const (
	Cluster_ROUND_ROBIN   Cluster_LbPolicy = 0
	Cluster_LEAST_REQUEST Cluster_LbPolicy = 1
	Cluster_RING_HASH     Cluster_LbPolicy = 2
	Cluster_RANDOM        Cluster_LbPolicy = 3
)

// Enum value maps for Cluster_LbPolicy.
var (
	Cluster_LbPolicy_name = map[int32]string{
		0: "ROUND_ROBIN",
		1: "LEAST_REQUEST",
		2: "RING_HASH",
		3: "RANDOM",
	}
	Cluster_LbPolicy_value = map[string]int32{
		"ROUND_ROBIN":   0,
		"LEAST_REQUEST": 1,
		"RING_HASH":     2,
		"RANDOM":        3,
	}
)

func (x Cluster_LbPolicy) Enum() *Cluster_LbPolicy {
	p := new(Cluster_LbPolicy)
	*p = x
	return p
}

func (x Cluster_LbPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cluster_LbPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_v1_cluster_proto_enumTypes[1].Descriptor()
}

func (Cluster_LbPolicy) Type() protoreflect.EnumType {
	return &file_cluster_v1_cluster_proto_enumTypes[1]
}

func (x Cluster_LbPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cluster_LbPolicy.Descriptor instead.
func (Cluster_LbPolicy) EnumDescriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0, 1}
}

type Cluster struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AltStatName string                 `protobuf:"bytes,28,opt,name=alt_stat_name,json=altStatName,proto3" json:"alt_stat_name,omitempty"`
	// Types that are valid to be assigned to ClusterDiscoveryType:
	//
	//	*Cluster_Type
	ClusterDiscoveryType          isCluster_ClusterDiscoveryType `protobuf_oneof:"cluster_discovery_type"`
	EdsClusterConfig              *Cluster_EdsClusterConfig      `protobuf:"bytes,3,opt,name=eds_cluster_config,json=edsClusterConfig,proto3" json:"eds_cluster_config,omitempty"`
	ConnectTimeout                *durationpb.Duration           `protobuf:"bytes,4,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	PerConnectionBufferLimitBytes *wrapperspb.UInt32Value        `protobuf:"bytes,5,opt,name=per_connection_buffer_limit_bytes,json=perConnectionBufferLimitBytes,proto3" json:"per_connection_buffer_limit_bytes,omitempty"`
	LbPolicy                      Cluster_LbPolicy               `protobuf:"varint,6,opt,name=lb_policy,json=lbPolicy,proto3,enum=cluster.v1.Cluster_LbPolicy" json:"lb_policy,omitempty"`
	LoadAssignment                *v1.ClusterLoadAssignment      `protobuf:"bytes,33,opt,name=load_assignment,json=loadAssignment,proto3" json:"load_assignment,omitempty"`
	CommonLbConfig                *Cluster_CommonLbConfig        `protobuf:"bytes,27,opt,name=common_lb_config,json=commonLbConfig,proto3" json:"common_lb_config,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetAltStatName() string {
	if x != nil {
		return x.AltStatName
	}
	return ""
}

func (x *Cluster) GetClusterDiscoveryType() isCluster_ClusterDiscoveryType {
	if x != nil {
		return x.ClusterDiscoveryType
	}
	return nil
}

func (x *Cluster) GetType() Cluster_DiscoveryType {
	if x != nil {
		if x, ok := x.ClusterDiscoveryType.(*Cluster_Type); ok {
			return x.Type
		}
	}
	return Cluster_STATIC
}

func (x *Cluster) GetEdsClusterConfig() *Cluster_EdsClusterConfig {
	if x != nil {
		return x.EdsClusterConfig
	}
	return nil
}

func (x *Cluster) GetConnectTimeout() *durationpb.Duration {
	if x != nil {
		return x.ConnectTimeout
	}
	return nil
}

func (x *Cluster) GetPerConnectionBufferLimitBytes() *wrapperspb.UInt32Value {
	if x != nil {
		return x.PerConnectionBufferLimitBytes
	}
	return nil
}

func (x *Cluster) GetLbPolicy() Cluster_LbPolicy {
	if x != nil {
		return x.LbPolicy
	}
	return Cluster_ROUND_ROBIN
}

func (x *Cluster) GetLoadAssignment() *v1.ClusterLoadAssignment {
	if x != nil {
		return x.LoadAssignment
	}
	return nil
}

func (x *Cluster) GetCommonLbConfig() *Cluster_CommonLbConfig {
	if x != nil {
		return x.CommonLbConfig
	}
	return nil
}

type isCluster_ClusterDiscoveryType interface {
	isCluster_ClusterDiscoveryType()
}

type Cluster_Type struct {
	Type Cluster_DiscoveryType `protobuf:"varint,2,opt,name=type,proto3,enum=cluster.v1.Cluster_DiscoveryType,oneof"`
}

func (*Cluster_Type) isCluster_ClusterDiscoveryType() {}

type Cluster_EdsClusterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdsConfig     *v11.ConfigSource      `protobuf:"bytes,1,opt,name=eds_config,json=edsConfig,proto3" json:"eds_config,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster_EdsClusterConfig) Reset() {
	*x = Cluster_EdsClusterConfig{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster_EdsClusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster_EdsClusterConfig) ProtoMessage() {}

func (x *Cluster_EdsClusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster_EdsClusterConfig.ProtoReflect.Descriptor instead.
func (*Cluster_EdsClusterConfig) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Cluster_EdsClusterConfig) GetEdsConfig() *v11.ConfigSource {
	if x != nil {
		return x.EdsConfig
	}
	return nil
}

func (x *Cluster_EdsClusterConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Cluster_CommonLbConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster_CommonLbConfig) Reset() {
	*x = Cluster_CommonLbConfig{}
	mi := &file_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster_CommonLbConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster_CommonLbConfig) ProtoMessage() {}

func (x *Cluster_CommonLbConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster_CommonLbConfig.ProtoReflect.Descriptor instead.
func (*Cluster_CommonLbConfig) Descriptor() ([]byte, []int) {
	return file_cluster_v1_cluster_proto_rawDescGZIP(), []int{0, 1}
}

var File_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x18cluster/v1/cluster.proto\x12\n" +
	"cluster.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x12core/v1/base.proto\x1a\x1bcore/v1/config_source.proto\x1a\x1aendpoint/v1/endpoint.proto\"\xfb\x06\n" +
	"\aCluster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\ralt_stat_name\x18\x1c \x01(\tR\valtStatName\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2!.cluster.v1.Cluster.DiscoveryTypeH\x00R\x04type\x12R\n" +
	"\x12eds_cluster_config\x18\x03 \x01(\v2$.cluster.v1.Cluster.EdsClusterConfigR\x10edsClusterConfig\x12B\n" +
	"\x0fconnect_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0econnectTimeout\x12f\n" +
	"!per_connection_buffer_limit_bytes\x18\x05 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x1dperConnectionBufferLimitBytes\x129\n" +
	"\tlb_policy\x18\x06 \x01(\x0e2\x1c.cluster.v1.Cluster.LbPolicyR\blbPolicy\x12K\n" +
	"\x0fload_assignment\x18! \x01(\v2\".endpoint.v1.ClusterLoadAssignmentR\x0eloadAssignment\x12L\n" +
	"\x10common_lb_config\x18\x1b \x01(\v2\".cluster.v1.Cluster.CommonLbConfigR\x0ecommonLbConfig\x1ak\n" +
	"\x10EdsClusterConfig\x124\n" +
	"\n" +
	"eds_config\x18\x01 \x01(\v2\x15.core.v1.ConfigSourceR\tedsConfig\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x1a\x10\n" +
	"\x0eCommonLbConfig\"E\n" +
	"\rDiscoveryType\x12\n" +
	"\n" +
	"\x06STATIC\x10\x00\x12\x0e\n" +
	"\n" +
	"STRICT_DNS\x10\x01\x12\x0f\n" +
	"\vLOGICAL_DNS\x10\x02\x12\a\n" +
	"\x03EDS\x10\x03\"I\n" +
	"\bLbPolicy\x12\x0f\n" +
	"\vROUND_ROBIN\x10\x00\x12\x11\n" +
	"\rLEAST_REQUEST\x10\x01\x12\r\n" +
	"\tRING_HASH\x10\x02\x12\n" +
	"\n" +
	"\x06RANDOM\x10\x03B\x18\n" +
	"\x16cluster_discovery_typeB:Z8github.com/dubbo-kubernetes/xds-api/cluster/v1;clusterv1b\x06proto3"

var (
	file_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_cluster_v1_cluster_proto_rawDescData []byte
)

func file_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_v1_cluster_proto_rawDesc), len(file_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_cluster_v1_cluster_proto_rawDescData
}

var file_cluster_v1_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cluster_v1_cluster_proto_goTypes = []any{
	(Cluster_DiscoveryType)(0),       // 0: cluster.v1.Cluster.DiscoveryType
	(Cluster_LbPolicy)(0),            // 1: cluster.v1.Cluster.LbPolicy
	(*Cluster)(nil),                  // 2: cluster.v1.Cluster
	(*Cluster_EdsClusterConfig)(nil), // 3: cluster.v1.Cluster.EdsClusterConfig
	(*Cluster_CommonLbConfig)(nil),   // 4: cluster.v1.Cluster.CommonLbConfig
	(*durationpb.Duration)(nil),      // 5: google.protobuf.Duration
	(*wrapperspb.UInt32Value)(nil),   // 6: google.protobuf.UInt32Value
	(*v1.ClusterLoadAssignment)(nil), // 7: endpoint.v1.ClusterLoadAssignment
	(*v11.ConfigSource)(nil),         // 8: core.v1.ConfigSource
}
var file_cluster_v1_cluster_proto_depIdxs = []int32{
	0, // 0: cluster.v1.Cluster.type:type_name -> cluster.v1.Cluster.DiscoveryType
	3, // 1: cluster.v1.Cluster.eds_cluster_config:type_name -> cluster.v1.Cluster.EdsClusterConfig
	5, // 2: cluster.v1.Cluster.connect_timeout:type_name -> google.protobuf.Duration
	6, // 3: cluster.v1.Cluster.per_connection_buffer_limit_bytes:type_name -> google.protobuf.UInt32Value
	1, // 4: cluster.v1.Cluster.lb_policy:type_name -> cluster.v1.Cluster.LbPolicy
	7, // 5: cluster.v1.Cluster.load_assignment:type_name -> endpoint.v1.ClusterLoadAssignment
	4, // 6: cluster.v1.Cluster.common_lb_config:type_name -> cluster.v1.Cluster.CommonLbConfig
	8, // 7: cluster.v1.Cluster.EdsClusterConfig.eds_config:type_name -> core.v1.ConfigSource
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_cluster_v1_cluster_proto_init() }
func file_cluster_v1_cluster_proto_init() {
	if File_cluster_v1_cluster_proto != nil {
		return
	}
	file_cluster_v1_cluster_proto_msgTypes[0].OneofWrappers = []any{
		(*Cluster_Type)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_v1_cluster_proto_rawDesc), len(file_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_v1_cluster_proto_depIdxs,
		EnumInfos:         file_cluster_v1_cluster_proto_enumTypes,
		MessageInfos:      file_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_cluster_v1_cluster_proto = out.File
	file_cluster_v1_cluster_proto_goTypes = nil
	file_cluster_v1_cluster_proto_depIdxs = nil
}
