// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: service/discovery/v1/ads.proto

package discoveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_discovery_v1_ads_proto protoreflect.FileDescriptor

const file_service_discovery_v1_ads_proto_rawDesc = "" +
	"\n" +
	"\x1eservice/discovery/v1/ads.proto\x12\x14service.discovery.v1\x1a$service/discovery/v1/discovery.proto2\x89\x02\n" +
	"\x1aAggregatedDiscoveryService\x12p\n" +
	"\x19StreamAggregatedResources\x12&.service.discovery.v1.DiscoveryRequest\x1a'.service.discovery.v1.DiscoveryResponse(\x010\x01\x12y\n" +
	"\x18DeltaAggregatedResources\x12+.service.discovery.v1.DeltaDiscoveryRequest\x1a,.service.discovery.v1.DeltaDiscoveryResponse(\x010\x01BFZDgithub.com/dubbo-kubernetes/xds-api/service/discovery/v1;discoveryv1b\x06proto3"

var file_service_discovery_v1_ads_proto_goTypes = []any{
	(*DiscoveryRequest)(nil),       // 0: service.discovery.v1.DiscoveryRequest
	(*DeltaDiscoveryRequest)(nil),  // 1: service.discovery.v1.DeltaDiscoveryRequest
	(*DiscoveryResponse)(nil),      // 2: service.discovery.v1.DiscoveryResponse
	(*DeltaDiscoveryResponse)(nil), // 3: service.discovery.v1.DeltaDiscoveryResponse
}
var file_service_discovery_v1_ads_proto_depIdxs = []int32{
	0, // 0: service.discovery.v1.AggregatedDiscoveryService.StreamAggregatedResources:input_type -> service.discovery.v1.DiscoveryRequest
	1, // 1: service.discovery.v1.AggregatedDiscoveryService.DeltaAggregatedResources:input_type -> service.discovery.v1.DeltaDiscoveryRequest
	2, // 2: service.discovery.v1.AggregatedDiscoveryService.StreamAggregatedResources:output_type -> service.discovery.v1.DiscoveryResponse
	3, // 3: service.discovery.v1.AggregatedDiscoveryService.DeltaAggregatedResources:output_type -> service.discovery.v1.DeltaDiscoveryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_discovery_v1_ads_proto_init() }
func file_service_discovery_v1_ads_proto_init() {
	if File_service_discovery_v1_ads_proto != nil {
		return
	}
	file_service_discovery_v1_discovery_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_discovery_v1_ads_proto_rawDesc), len(file_service_discovery_v1_ads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_discovery_v1_ads_proto_goTypes,
		DependencyIndexes: file_service_discovery_v1_ads_proto_depIdxs,
	}.Build()
	File_service_discovery_v1_ads_proto = out.File
	file_service_discovery_v1_ads_proto_goTypes = nil
	file_service_discovery_v1_ads_proto_depIdxs = nil
}
