// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: service/discovery/v1/discovery.proto

package discoveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionInfo   string                 `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	ResourceNames []string               `protobuf:"bytes,3,rep,name=resource_names,json=resourceNames,proto3" json:"resource_names,omitempty"`
	TypeUrl       string                 `protobuf:"bytes,4,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	ResponseNonce string                 `protobuf:"bytes,5,opt,name=response_nonce,json=responseNonce,proto3" json:"response_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_service_discovery_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryRequest) GetVersionInfo() string {
	if x != nil {
		return x.VersionInfo
	}
	return ""
}

func (x *DiscoveryRequest) GetResourceNames() []string {
	if x != nil {
		return x.ResourceNames
	}
	return nil
}

func (x *DiscoveryRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DiscoveryRequest) GetResponseNonce() string {
	if x != nil {
		return x.ResponseNonce
	}
	return ""
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionInfo   string                 `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	Resources     []*anypb.Any           `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Canary        bool                   `protobuf:"varint,3,opt,name=canary,proto3" json:"canary,omitempty"`
	TypeUrl       string                 `protobuf:"bytes,4,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Nonce         string                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_service_discovery_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryResponse) GetVersionInfo() string {
	if x != nil {
		return x.VersionInfo
	}
	return ""
}

func (x *DiscoveryResponse) GetResources() []*anypb.Any {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DiscoveryResponse) GetCanary() bool {
	if x != nil {
		return x.Canary
	}
	return false
}

func (x *DiscoveryResponse) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DiscoveryResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type DeltaDiscoveryRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl                  string                 `protobuf:"bytes,2,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	ResourceNamesSubscribe   []string               `protobuf:"bytes,3,rep,name=resource_names_subscribe,json=resourceNamesSubscribe,proto3" json:"resource_names_subscribe,omitempty"`
	ResourceNamesUnsubscribe []string               `protobuf:"bytes,4,rep,name=resource_names_unsubscribe,json=resourceNamesUnsubscribe,proto3" json:"resource_names_unsubscribe,omitempty"`
	InitialResourceVersions  map[string]string      `protobuf:"bytes,5,rep,name=initial_resource_versions,json=initialResourceVersions,proto3" json:"initial_resource_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseNonce            string                 `protobuf:"bytes,6,opt,name=response_nonce,json=responseNonce,proto3" json:"response_nonce,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeltaDiscoveryRequest) Reset() {
	*x = DeltaDiscoveryRequest{}
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaDiscoveryRequest) ProtoMessage() {}

func (x *DeltaDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DeltaDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_service_discovery_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *DeltaDiscoveryRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DeltaDiscoveryRequest) GetResourceNamesSubscribe() []string {
	if x != nil {
		return x.ResourceNamesSubscribe
	}
	return nil
}

func (x *DeltaDiscoveryRequest) GetResourceNamesUnsubscribe() []string {
	if x != nil {
		return x.ResourceNamesUnsubscribe
	}
	return nil
}

func (x *DeltaDiscoveryRequest) GetInitialResourceVersions() map[string]string {
	if x != nil {
		return x.InitialResourceVersions
	}
	return nil
}

func (x *DeltaDiscoveryRequest) GetResponseNonce() string {
	if x != nil {
		return x.ResponseNonce
	}
	return ""
}

type DeltaDiscoveryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SystemVersionInfo string                 `protobuf:"bytes,1,opt,name=system_version_info,json=systemVersionInfo,proto3" json:"system_version_info,omitempty"`
	Resources         []*Resource            `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	TypeUrl           string                 `protobuf:"bytes,3,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	RemovedResources  []string               `protobuf:"bytes,4,rep,name=removed_resources,json=removedResources,proto3" json:"removed_resources,omitempty"`
	Nonce             string                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeltaDiscoveryResponse) Reset() {
	*x = DeltaDiscoveryResponse{}
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaDiscoveryResponse) ProtoMessage() {}

func (x *DeltaDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DeltaDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_service_discovery_v1_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *DeltaDiscoveryResponse) GetSystemVersionInfo() string {
	if x != nil {
		return x.SystemVersionInfo
	}
	return ""
}

func (x *DeltaDiscoveryResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DeltaDiscoveryResponse) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DeltaDiscoveryResponse) GetRemovedResources() []string {
	if x != nil {
		return x.RemovedResources
	}
	return nil
}

func (x *DeltaDiscoveryResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// [#next-free-field: 10]
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Aliases       []string               `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Resource      *anypb.Any             `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	CacheControl  *Resource_CacheControl `protobuf:"bytes,6,opt,name=cache_control,json=cacheControl,proto3" json:"cache_control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_service_discovery_v1_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *Resource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Resource) GetResource() *anypb.Any {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Resource) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Resource) GetCacheControl() *Resource_CacheControl {
	if x != nil {
		return x.CacheControl
	}
	return nil
}

type Resource_CacheControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoNotCache    bool                   `protobuf:"varint,1,opt,name=do_not_cache,json=doNotCache,proto3" json:"do_not_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource_CacheControl) Reset() {
	*x = Resource_CacheControl{}
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource_CacheControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource_CacheControl) ProtoMessage() {}

func (x *Resource_CacheControl) ProtoReflect() protoreflect.Message {
	mi := &file_service_discovery_v1_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource_CacheControl.ProtoReflect.Descriptor instead.
func (*Resource_CacheControl) Descriptor() ([]byte, []int) {
	return file_service_discovery_v1_discovery_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Resource_CacheControl) GetDoNotCache() bool {
	if x != nil {
		return x.DoNotCache
	}
	return false
}

var File_service_discovery_v1_discovery_proto protoreflect.FileDescriptor

const file_service_discovery_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"$service/discovery/v1/discovery.proto\x12\x14service.discovery.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"\x9e\x01\n" +
	"\x10DiscoveryRequest\x12!\n" +
	"\fversion_info\x18\x01 \x01(\tR\vversionInfo\x12%\n" +
	"\x0eresource_names\x18\x03 \x03(\tR\rresourceNames\x12\x19\n" +
	"\btype_url\x18\x04 \x01(\tR\atypeUrl\x12%\n" +
	"\x0eresponse_nonce\x18\x05 \x01(\tR\rresponseNonce\"\xb3\x01\n" +
	"\x11DiscoveryResponse\x12!\n" +
	"\fversion_info\x18\x01 \x01(\tR\vversionInfo\x122\n" +
	"\tresources\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\tresources\x12\x16\n" +
	"\x06canary\x18\x03 \x01(\bR\x06canary\x12\x19\n" +
	"\btype_url\x18\x04 \x01(\tR\atypeUrl\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\tR\x05nonce\"\xa4\x03\n" +
	"\x15DeltaDiscoveryRequest\x12\x19\n" +
	"\btype_url\x18\x02 \x01(\tR\atypeUrl\x128\n" +
	"\x18resource_names_subscribe\x18\x03 \x03(\tR\x16resourceNamesSubscribe\x12<\n" +
	"\x1aresource_names_unsubscribe\x18\x04 \x03(\tR\x18resourceNamesUnsubscribe\x12\x84\x01\n" +
	"\x19initial_resource_versions\x18\x05 \x03(\v2H.service.discovery.v1.DeltaDiscoveryRequest.InitialResourceVersionsEntryR\x17initialResourceVersions\x12%\n" +
	"\x0eresponse_nonce\x18\x06 \x01(\tR\rresponseNonce\x1aJ\n" +
	"\x1cInitialResourceVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\x16DeltaDiscoveryResponse\x12.\n" +
	"\x13system_version_info\x18\x01 \x01(\tR\x11systemVersionInfo\x12<\n" +
	"\tresources\x18\x02 \x03(\v2\x1e.service.discovery.v1.ResourceR\tresources\x12\x19\n" +
	"\btype_url\x18\x03 \x01(\tR\atypeUrl\x12+\n" +
	"\x11removed_resources\x18\x04 \x03(\tR\x10removedResources\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\tR\x05nonce\"\xb5\x02\n" +
	"\bResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x120\n" +
	"\bresource\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\bresource\x12+\n" +
	"\x03ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12P\n" +
	"\rcache_control\x18\x06 \x01(\v2+.service.discovery.v1.Resource.CacheControlR\fcacheControl\x1a0\n" +
	"\fCacheControl\x12 \n" +
	"\fdo_not_cache\x18\x01 \x01(\bR\n" +
	"doNotCacheBFZDgithub.com/dubbo-kubernetes/xds-api/service/discovery/v1;discoveryv1b\x06proto3"

var (
	file_service_discovery_v1_discovery_proto_rawDescOnce sync.Once
	file_service_discovery_v1_discovery_proto_rawDescData []byte
)

func file_service_discovery_v1_discovery_proto_rawDescGZIP() []byte {
	file_service_discovery_v1_discovery_proto_rawDescOnce.Do(func() {
		file_service_discovery_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_discovery_v1_discovery_proto_rawDesc), len(file_service_discovery_v1_discovery_proto_rawDesc)))
	})
	return file_service_discovery_v1_discovery_proto_rawDescData
}

var file_service_discovery_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_discovery_v1_discovery_proto_goTypes = []any{
	(*DiscoveryRequest)(nil),       // 0: service.discovery.v1.DiscoveryRequest
	(*DiscoveryResponse)(nil),      // 1: service.discovery.v1.DiscoveryResponse
	(*DeltaDiscoveryRequest)(nil),  // 2: service.discovery.v1.DeltaDiscoveryRequest
	(*DeltaDiscoveryResponse)(nil), // 3: service.discovery.v1.DeltaDiscoveryResponse
	(*Resource)(nil),               // 4: service.discovery.v1.Resource
	nil,                            // 5: service.discovery.v1.DeltaDiscoveryRequest.InitialResourceVersionsEntry
	(*Resource_CacheControl)(nil),  // 6: service.discovery.v1.Resource.CacheControl
	(*anypb.Any)(nil),              // 7: google.protobuf.Any
	(*durationpb.Duration)(nil),    // 8: google.protobuf.Duration
}
var file_service_discovery_v1_discovery_proto_depIdxs = []int32{
	7, // 0: service.discovery.v1.DiscoveryResponse.resources:type_name -> google.protobuf.Any
	5, // 1: service.discovery.v1.DeltaDiscoveryRequest.initial_resource_versions:type_name -> service.discovery.v1.DeltaDiscoveryRequest.InitialResourceVersionsEntry
	4, // 2: service.discovery.v1.DeltaDiscoveryResponse.resources:type_name -> service.discovery.v1.Resource
	7, // 3: service.discovery.v1.Resource.resource:type_name -> google.protobuf.Any
	8, // 4: service.discovery.v1.Resource.ttl:type_name -> google.protobuf.Duration
	6, // 5: service.discovery.v1.Resource.cache_control:type_name -> service.discovery.v1.Resource.CacheControl
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_service_discovery_v1_discovery_proto_init() }
func file_service_discovery_v1_discovery_proto_init() {
	if File_service_discovery_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_discovery_v1_discovery_proto_rawDesc), len(file_service_discovery_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_discovery_v1_discovery_proto_goTypes,
		DependencyIndexes: file_service_discovery_v1_discovery_proto_depIdxs,
		MessageInfos:      file_service_discovery_v1_discovery_proto_msgTypes,
	}.Build()
	File_service_discovery_v1_discovery_proto = out.File
	file_service_discovery_v1_discovery_proto_goTypes = nil
	file_service_discovery_v1_discovery_proto_depIdxs = nil
}
