// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: endpoint/v1/endpoint.proto

package endpointv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterLoadAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Endpoints     []*LocalityLbEndpoints `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterLoadAssignment) Reset() {
	*x = ClusterLoadAssignment{}
	mi := &file_endpoint_v1_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterLoadAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterLoadAssignment) ProtoMessage() {}

func (x *ClusterLoadAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_v1_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterLoadAssignment.ProtoReflect.Descriptor instead.
func (*ClusterLoadAssignment) Descriptor() ([]byte, []int) {
	return file_endpoint_v1_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterLoadAssignment) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ClusterLoadAssignment) GetEndpoints() []*LocalityLbEndpoints {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_endpoint_v1_endpoint_proto protoreflect.FileDescriptor

const file_endpoint_v1_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x1aendpoint/v1/endpoint.proto\x12\vendpoint.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a%endpoint/v1/endpoint_components.proto\"z\n" +
	"\x15ClusterLoadAssignment\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12>\n" +
	"\tendpoints\x18\x02 \x03(\v2 .endpoint.v1.LocalityLbEndpointsR\tendpointsB<Z:github.com/dubbo-kubernetes/xds-api/endpoint/v1;endpointv1b\x06proto3"

var (
	file_endpoint_v1_endpoint_proto_rawDescOnce sync.Once
	file_endpoint_v1_endpoint_proto_rawDescData []byte
)

func file_endpoint_v1_endpoint_proto_rawDescGZIP() []byte {
	file_endpoint_v1_endpoint_proto_rawDescOnce.Do(func() {
		file_endpoint_v1_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoint_v1_endpoint_proto_rawDesc), len(file_endpoint_v1_endpoint_proto_rawDesc)))
	})
	return file_endpoint_v1_endpoint_proto_rawDescData
}

var file_endpoint_v1_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_endpoint_v1_endpoint_proto_goTypes = []any{
	(*ClusterLoadAssignment)(nil), // 0: endpoint.v1.ClusterLoadAssignment
	(*LocalityLbEndpoints)(nil),   // 1: endpoint.v1.LocalityLbEndpoints
}
var file_endpoint_v1_endpoint_proto_depIdxs = []int32{
	1, // 0: endpoint.v1.ClusterLoadAssignment.endpoints:type_name -> endpoint.v1.LocalityLbEndpoints
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_endpoint_v1_endpoint_proto_init() }
func file_endpoint_v1_endpoint_proto_init() {
	if File_endpoint_v1_endpoint_proto != nil {
		return
	}
	file_endpoint_v1_endpoint_components_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoint_v1_endpoint_proto_rawDesc), len(file_endpoint_v1_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpoint_v1_endpoint_proto_goTypes,
		DependencyIndexes: file_endpoint_v1_endpoint_proto_depIdxs,
		MessageInfos:      file_endpoint_v1_endpoint_proto_msgTypes,
	}.Build()
	File_endpoint_v1_endpoint_proto = out.File
	file_endpoint_v1_endpoint_proto_goTypes = nil
	file_endpoint_v1_endpoint_proto_depIdxs = nil
}
