// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: core/v1/config_source.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiVersion int32

const (
	ApiVersion_AUTO ApiVersion = 0
)

// Enum value maps for ApiVersion.
var (
	ApiVersion_name = map[int32]string{
		0: "AUTO",
	}
	ApiVersion_value = map[string]int32{
		"AUTO": 0,
	}
)

func (x ApiVersion) Enum() *ApiVersion {
	p := new(ApiVersion)
	*p = x
	return p
}

func (x ApiVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_core_v1_config_source_proto_enumTypes[0].Descriptor()
}

func (ApiVersion) Type() protoreflect.EnumType {
	return &file_core_v1_config_source_proto_enumTypes[0]
}

func (x ApiVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiVersion.Descriptor instead.
func (ApiVersion) EnumDescriptor() ([]byte, []int) {
	return file_core_v1_config_source_proto_rawDescGZIP(), []int{0}
}

type ApiConfigSource_ApiType int32

const (
	ApiConfigSource_REST                  ApiConfigSource_ApiType = 0
	ApiConfigSource_GRPC                  ApiConfigSource_ApiType = 1
	ApiConfigSource_DELTA_GRPC            ApiConfigSource_ApiType = 2
	ApiConfigSource_AGGREGATED_GRPC       ApiConfigSource_ApiType = 3
	ApiConfigSource_AGGREGATED_DELTA_GRPC ApiConfigSource_ApiType = 4
)

// Enum value maps for ApiConfigSource_ApiType.
var (
	ApiConfigSource_ApiType_name = map[int32]string{
		0: "REST",
		1: "GRPC",
		2: "DELTA_GRPC",
		3: "AGGREGATED_GRPC",
		4: "AGGREGATED_DELTA_GRPC",
	}
	ApiConfigSource_ApiType_value = map[string]int32{
		"REST":                  0,
		"GRPC":                  1,
		"DELTA_GRPC":            2,
		"AGGREGATED_GRPC":       3,
		"AGGREGATED_DELTA_GRPC": 4,
	}
)

func (x ApiConfigSource_ApiType) Enum() *ApiConfigSource_ApiType {
	p := new(ApiConfigSource_ApiType)
	*p = x
	return p
}

func (x ApiConfigSource_ApiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiConfigSource_ApiType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_v1_config_source_proto_enumTypes[1].Descriptor()
}

func (ApiConfigSource_ApiType) Type() protoreflect.EnumType {
	return &file_core_v1_config_source_proto_enumTypes[1]
}

func (x ApiConfigSource_ApiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiConfigSource_ApiType.Descriptor instead.
func (ApiConfigSource_ApiType) EnumDescriptor() ([]byte, []int) {
	return file_core_v1_config_source_proto_rawDescGZIP(), []int{0, 0}
}

type ApiConfigSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiConfigSource) Reset() {
	*x = ApiConfigSource{}
	mi := &file_core_v1_config_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiConfigSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiConfigSource) ProtoMessage() {}

func (x *ApiConfigSource) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_config_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiConfigSource.ProtoReflect.Descriptor instead.
func (*ApiConfigSource) Descriptor() ([]byte, []int) {
	return file_core_v1_config_source_proto_rawDescGZIP(), []int{0}
}

type ConfigSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ConfigSourceSpecifier:
	//
	//	*ConfigSource_ApiConfigSource
	ConfigSourceSpecifier isConfigSource_ConfigSourceSpecifier `protobuf_oneof:"config_source_specifier"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConfigSource) Reset() {
	*x = ConfigSource{}
	mi := &file_core_v1_config_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSource) ProtoMessage() {}

func (x *ConfigSource) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_config_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSource.ProtoReflect.Descriptor instead.
func (*ConfigSource) Descriptor() ([]byte, []int) {
	return file_core_v1_config_source_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSource) GetConfigSourceSpecifier() isConfigSource_ConfigSourceSpecifier {
	if x != nil {
		return x.ConfigSourceSpecifier
	}
	return nil
}

func (x *ConfigSource) GetApiConfigSource() *ApiConfigSource {
	if x != nil {
		if x, ok := x.ConfigSourceSpecifier.(*ConfigSource_ApiConfigSource); ok {
			return x.ApiConfigSource
		}
	}
	return nil
}

type isConfigSource_ConfigSourceSpecifier interface {
	isConfigSource_ConfigSourceSpecifier()
}

type ConfigSource_ApiConfigSource struct {
	ApiConfigSource *ApiConfigSource `protobuf:"bytes,2,opt,name=api_config_source,json=apiConfigSource,proto3,oneof"`
}

func (*ConfigSource_ApiConfigSource) isConfigSource_ConfigSourceSpecifier() {}

var File_core_v1_config_source_proto protoreflect.FileDescriptor

const file_core_v1_config_source_proto_rawDesc = "" +
	"\n" +
	"\x1bcore/v1/config_source.proto\x12\acore.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"p\n" +
	"\x0fApiConfigSource\"]\n" +
	"\aApiType\x12\b\n" +
	"\x04REST\x10\x00\x12\b\n" +
	"\x04GRPC\x10\x01\x12\x0e\n" +
	"\n" +
	"DELTA_GRPC\x10\x02\x12\x13\n" +
	"\x0fAGGREGATED_GRPC\x10\x03\x12\x19\n" +
	"\x15AGGREGATED_DELTA_GRPC\x10\x04\"q\n" +
	"\fConfigSource\x12F\n" +
	"\x11api_config_source\x18\x02 \x01(\v2\x18.core.v1.ApiConfigSourceH\x00R\x0fapiConfigSourceB\x19\n" +
	"\x17config_source_specifier*\x16\n" +
	"\n" +
	"ApiVersion\x12\b\n" +
	"\x04AUTO\x10\x00B4Z2github.com/dubbo-kubernetes/xds-api/core/v1;corev1b\x06proto3"

var (
	file_core_v1_config_source_proto_rawDescOnce sync.Once
	file_core_v1_config_source_proto_rawDescData []byte
)

func file_core_v1_config_source_proto_rawDescGZIP() []byte {
	file_core_v1_config_source_proto_rawDescOnce.Do(func() {
		file_core_v1_config_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_config_source_proto_rawDesc), len(file_core_v1_config_source_proto_rawDesc)))
	})
	return file_core_v1_config_source_proto_rawDescData
}

var file_core_v1_config_source_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_core_v1_config_source_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_v1_config_source_proto_goTypes = []any{
	(ApiVersion)(0),              // 0: core.v1.ApiVersion
	(ApiConfigSource_ApiType)(0), // 1: core.v1.ApiConfigSource.ApiType
	(*ApiConfigSource)(nil),      // 2: core.v1.ApiConfigSource
	(*ConfigSource)(nil),         // 3: core.v1.ConfigSource
}
var file_core_v1_config_source_proto_depIdxs = []int32{
	2, // 0: core.v1.ConfigSource.api_config_source:type_name -> core.v1.ApiConfigSource
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_v1_config_source_proto_init() }
func file_core_v1_config_source_proto_init() {
	if File_core_v1_config_source_proto != nil {
		return
	}
	file_core_v1_config_source_proto_msgTypes[1].OneofWrappers = []any{
		(*ConfigSource_ApiConfigSource)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_config_source_proto_rawDesc), len(file_core_v1_config_source_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_config_source_proto_goTypes,
		DependencyIndexes: file_core_v1_config_source_proto_depIdxs,
		EnumInfos:         file_core_v1_config_source_proto_enumTypes,
		MessageInfos:      file_core_v1_config_source_proto_msgTypes,
	}.Build()
	File_core_v1_config_source_proto = out.File
	file_core_v1_config_source_proto_goTypes = nil
	file_core_v1_config_source_proto_depIdxs = nil
}
