// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: core/v1/health_check.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_UNKNOWN   HealthStatus = 0
	HealthStatus_HEALTHY   HealthStatus = 1
	HealthStatus_UNHEALTHY HealthStatus = 2
	HealthStatus_DRAINING  HealthStatus = 3
	HealthStatus_TIMEOUT   HealthStatus = 4
	HealthStatus_DEGRADED  HealthStatus = 5
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "DRAINING",
		4: "TIMEOUT",
		5: "DEGRADED",
	}
	HealthStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"UNHEALTHY": 2,
		"DRAINING":  3,
		"TIMEOUT":   4,
		"DEGRADED":  5,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_core_v1_health_check_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_core_v1_health_check_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_core_v1_health_check_proto_rawDescGZIP(), []int{0}
}

var File_core_v1_health_check_proto protoreflect.FileDescriptor

const file_core_v1_health_check_proto_rawDesc = "" +
	"\n" +
	"\x1acore/v1/health_check.proto\x12\acore.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto*`\n" +
	"\fHealthStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\x12\f\n" +
	"\bDRAINING\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\f\n" +
	"\bDEGRADED\x10\x05B4Z2github.com/dubbo-kubernetes/xds-api/core/v1;corev1b\x06proto3"

var (
	file_core_v1_health_check_proto_rawDescOnce sync.Once
	file_core_v1_health_check_proto_rawDescData []byte
)

func file_core_v1_health_check_proto_rawDescGZIP() []byte {
	file_core_v1_health_check_proto_rawDescOnce.Do(func() {
		file_core_v1_health_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_health_check_proto_rawDesc), len(file_core_v1_health_check_proto_rawDesc)))
	})
	return file_core_v1_health_check_proto_rawDescData
}

var file_core_v1_health_check_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_v1_health_check_proto_goTypes = []any{
	(HealthStatus)(0), // 0: core.v1.HealthStatus
}
var file_core_v1_health_check_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_v1_health_check_proto_init() }
func file_core_v1_health_check_proto_init() {
	if File_core_v1_health_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_health_check_proto_rawDesc), len(file_core_v1_health_check_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_health_check_proto_goTypes,
		DependencyIndexes: file_core_v1_health_check_proto_depIdxs,
		EnumInfos:         file_core_v1_health_check_proto_enumTypes,
	}.Build()
	File_core_v1_health_check_proto = out.File
	file_core_v1_health_check_proto_goTypes = nil
	file_core_v1_health_check_proto_depIdxs = nil
}
