// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: extensions/filters/v1/network/http_connection_manager/http_connection_manager.proto

package http_connection_managerv1

import (
	v11 "github.com/dubbo-kubernetes/xds-api/core/v1"
	v1 "github.com/dubbo-kubernetes/xds-api/route/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpConnectionManager_CodecType int32

const (
	HttpConnectionManager_AUTO HttpConnectionManager_CodecType = 0
)

// Enum value maps for HttpConnectionManager_CodecType.
var (
	HttpConnectionManager_CodecType_name = map[int32]string{
		0: "AUTO",
	}
	HttpConnectionManager_CodecType_value = map[string]int32{
		"AUTO": 0,
	}
)

func (x HttpConnectionManager_CodecType) Enum() *HttpConnectionManager_CodecType {
	p := new(HttpConnectionManager_CodecType)
	*p = x
	return p
}

func (x HttpConnectionManager_CodecType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpConnectionManager_CodecType) Descriptor() protoreflect.EnumDescriptor {
	return file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_enumTypes[0].Descriptor()
}

func (HttpConnectionManager_CodecType) Type() protoreflect.EnumType {
	return &file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_enumTypes[0]
}

func (x HttpConnectionManager_CodecType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpConnectionManager_CodecType.Descriptor instead.
func (HttpConnectionManager_CodecType) EnumDescriptor() ([]byte, []int) {
	return file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescGZIP(), []int{0, 0}
}

type HttpConnectionManager struct {
	state      protoimpl.MessageState          `protogen:"open.v1"`
	CodecType  HttpConnectionManager_CodecType `protobuf:"varint,1,opt,name=codec_type,json=codecType,proto3,enum=extensions.filters.network.http_connection_manager.v1.HttpConnectionManager_CodecType" json:"codec_type,omitempty"`
	StatPrefix string                          `protobuf:"bytes,2,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	// Types that are valid to be assigned to RouteSpecifier:
	//
	//	*HttpConnectionManager_Rds
	//	*HttpConnectionManager_RouteConfig
	RouteSpecifier isHttpConnectionManager_RouteSpecifier `protobuf_oneof:"route_specifier"`
	HttpFilters    []*HttpFilter                          `protobuf:"bytes,5,rep,name=http_filters,json=httpFilters,proto3" json:"http_filters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HttpConnectionManager) Reset() {
	*x = HttpConnectionManager{}
	mi := &file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpConnectionManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpConnectionManager) ProtoMessage() {}

func (x *HttpConnectionManager) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpConnectionManager.ProtoReflect.Descriptor instead.
func (*HttpConnectionManager) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescGZIP(), []int{0}
}

func (x *HttpConnectionManager) GetCodecType() HttpConnectionManager_CodecType {
	if x != nil {
		return x.CodecType
	}
	return HttpConnectionManager_AUTO
}

func (x *HttpConnectionManager) GetStatPrefix() string {
	if x != nil {
		return x.StatPrefix
	}
	return ""
}

func (x *HttpConnectionManager) GetRouteSpecifier() isHttpConnectionManager_RouteSpecifier {
	if x != nil {
		return x.RouteSpecifier
	}
	return nil
}

func (x *HttpConnectionManager) GetRds() *Rds {
	if x != nil {
		if x, ok := x.RouteSpecifier.(*HttpConnectionManager_Rds); ok {
			return x.Rds
		}
	}
	return nil
}

func (x *HttpConnectionManager) GetRouteConfig() *v1.RouteConfiguration {
	if x != nil {
		if x, ok := x.RouteSpecifier.(*HttpConnectionManager_RouteConfig); ok {
			return x.RouteConfig
		}
	}
	return nil
}

func (x *HttpConnectionManager) GetHttpFilters() []*HttpFilter {
	if x != nil {
		return x.HttpFilters
	}
	return nil
}

type isHttpConnectionManager_RouteSpecifier interface {
	isHttpConnectionManager_RouteSpecifier()
}

type HttpConnectionManager_Rds struct {
	Rds *Rds `protobuf:"bytes,3,opt,name=rds,proto3,oneof"`
}

type HttpConnectionManager_RouteConfig struct {
	RouteConfig *v1.RouteConfiguration `protobuf:"bytes,4,opt,name=route_config,json=routeConfig,proto3,oneof"`
}

func (*HttpConnectionManager_Rds) isHttpConnectionManager_RouteSpecifier() {}

func (*HttpConnectionManager_RouteConfig) isHttpConnectionManager_RouteSpecifier() {}

type Rds struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigSource    *v11.ConfigSource      `protobuf:"bytes,1,opt,name=config_source,json=configSource,proto3" json:"config_source,omitempty"`
	RouteConfigName string                 `protobuf:"bytes,2,opt,name=route_config_name,json=routeConfigName,proto3" json:"route_config_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Rds) Reset() {
	*x = Rds{}
	mi := &file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rds) ProtoMessage() {}

func (x *Rds) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rds.ProtoReflect.Descriptor instead.
func (*Rds) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescGZIP(), []int{1}
}

func (x *Rds) GetConfigSource() *v11.ConfigSource {
	if x != nil {
		return x.ConfigSource
	}
	return nil
}

func (x *Rds) GetRouteConfigName() string {
	if x != nil {
		return x.RouteConfigName
	}
	return ""
}

type HttpFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ConfigType:
	//
	//	*HttpFilter_TypedConfig
	ConfigType    isHttpFilter_ConfigType `protobuf_oneof:"config_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpFilter) Reset() {
	*x = HttpFilter{}
	mi := &file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpFilter) ProtoMessage() {}

func (x *HttpFilter) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpFilter.ProtoReflect.Descriptor instead.
func (*HttpFilter) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescGZIP(), []int{2}
}

func (x *HttpFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HttpFilter) GetConfigType() isHttpFilter_ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return nil
}

func (x *HttpFilter) GetTypedConfig() *anypb.Any {
	if x != nil {
		if x, ok := x.ConfigType.(*HttpFilter_TypedConfig); ok {
			return x.TypedConfig
		}
	}
	return nil
}

type isHttpFilter_ConfigType interface {
	isHttpFilter_ConfigType()
}

type HttpFilter_TypedConfig struct {
	TypedConfig *anypb.Any `protobuf:"bytes,4,opt,name=typed_config,json=typedConfig,proto3,oneof"`
}

func (*HttpFilter_TypedConfig) isHttpFilter_ConfigType() {}

var File_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto protoreflect.FileDescriptor

const file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDesc = "" +
	"\n" +
	"Sextensions/filters/v1/network/http_connection_manager/http_connection_manager.proto\x125extensions.filters.network.http_connection_manager.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x12core/v1/base.proto\x1a\x1bcore/v1/config_source.proto\x1a\x14route/v1/route.proto\"\xd2\x03\n" +
	"\x15HttpConnectionManager\x12u\n" +
	"\n" +
	"codec_type\x18\x01 \x01(\x0e2V.extensions.filters.network.http_connection_manager.v1.HttpConnectionManager.CodecTypeR\tcodecType\x12\x1f\n" +
	"\vstat_prefix\x18\x02 \x01(\tR\n" +
	"statPrefix\x12N\n" +
	"\x03rds\x18\x03 \x01(\v2:.extensions.filters.network.http_connection_manager.v1.RdsH\x00R\x03rds\x12A\n" +
	"\froute_config\x18\x04 \x01(\v2\x1c.route.v1.RouteConfigurationH\x00R\vrouteConfig\x12d\n" +
	"\fhttp_filters\x18\x05 \x03(\v2A.extensions.filters.network.http_connection_manager.v1.HttpFilterR\vhttpFilters\"\x15\n" +
	"\tCodecType\x12\b\n" +
	"\x04AUTO\x10\x00B\x11\n" +
	"\x0froute_specifier\"m\n" +
	"\x03Rds\x12:\n" +
	"\rconfig_source\x18\x01 \x01(\v2\x15.core.v1.ConfigSourceR\fconfigSource\x12*\n" +
	"\x11route_config_name\x18\x02 \x01(\tR\x0frouteConfigName\"j\n" +
	"\n" +
	"HttpFilter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\ftyped_config\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\vtypedConfigB\r\n" +
	"\vconfig_typeBuZsgithub.com/dubbo-kubernetes/xds-api/extensions/filters/network/http_connection_manager/v1;http_connection_managerv1b\x06proto3"

var (
	file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescOnce sync.Once
	file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescData []byte
)

func file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescGZIP() []byte {
	file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescOnce.Do(func() {
		file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDesc), len(file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDesc)))
	})
	return file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDescData
}

var file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_goTypes = []any{
	(HttpConnectionManager_CodecType)(0), // 0: extensions.filters.network.http_connection_manager.v1.HttpConnectionManager.CodecType
	(*HttpConnectionManager)(nil),        // 1: extensions.filters.network.http_connection_manager.v1.HttpConnectionManager
	(*Rds)(nil),                          // 2: extensions.filters.network.http_connection_manager.v1.Rds
	(*HttpFilter)(nil),                   // 3: extensions.filters.network.http_connection_manager.v1.HttpFilter
	(*v1.RouteConfiguration)(nil),        // 4: route.v1.RouteConfiguration
	(*v11.ConfigSource)(nil),             // 5: core.v1.ConfigSource
	(*anypb.Any)(nil),                    // 6: google.protobuf.Any
}
var file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_depIdxs = []int32{
	0, // 0: extensions.filters.network.http_connection_manager.v1.HttpConnectionManager.codec_type:type_name -> extensions.filters.network.http_connection_manager.v1.HttpConnectionManager.CodecType
	2, // 1: extensions.filters.network.http_connection_manager.v1.HttpConnectionManager.rds:type_name -> extensions.filters.network.http_connection_manager.v1.Rds
	4, // 2: extensions.filters.network.http_connection_manager.v1.HttpConnectionManager.route_config:type_name -> route.v1.RouteConfiguration
	3, // 3: extensions.filters.network.http_connection_manager.v1.HttpConnectionManager.http_filters:type_name -> extensions.filters.network.http_connection_manager.v1.HttpFilter
	5, // 4: extensions.filters.network.http_connection_manager.v1.Rds.config_source:type_name -> core.v1.ConfigSource
	6, // 5: extensions.filters.network.http_connection_manager.v1.HttpFilter.typed_config:type_name -> google.protobuf.Any
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() {
	file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_init()
}
func file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_init() {
	if File_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto != nil {
		return
	}
	file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes[0].OneofWrappers = []any{
		(*HttpConnectionManager_Rds)(nil),
		(*HttpConnectionManager_RouteConfig)(nil),
	}
	file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes[2].OneofWrappers = []any{
		(*HttpFilter_TypedConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDesc), len(file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_goTypes,
		DependencyIndexes: file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_depIdxs,
		EnumInfos:         file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_enumTypes,
		MessageInfos:      file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_msgTypes,
	}.Build()
	File_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto = out.File
	file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_goTypes = nil
	file_extensions_filters_v1_network_http_connection_manager_http_connection_manager_proto_depIdxs = nil
}
