// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: config/endpoint/v1/endpoint_components.proto

package endpointv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_config_endpoint_v1_endpoint_components_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_config_endpoint_v1_endpoint_components_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_config_endpoint_v1_endpoint_components_proto_rawDescGZIP(), []int{0}
}

type LbEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to HostIdentifier:
	//
	//	*LbEndpoint_Endpoint
	//	*LbEndpoint_EndpointName
	HostIdentifier      isLbEndpoint_HostIdentifier `protobuf_oneof:"host_identifier"`
	LoadBalancingWeight *wrapperspb.UInt32Value     `protobuf:"bytes,4,opt,name=load_balancing_weight,json=loadBalancingWeight,proto3" json:"load_balancing_weight,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LbEndpoint) Reset() {
	*x = LbEndpoint{}
	mi := &file_config_endpoint_v1_endpoint_components_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LbEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LbEndpoint) ProtoMessage() {}

func (x *LbEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_config_endpoint_v1_endpoint_components_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LbEndpoint.ProtoReflect.Descriptor instead.
func (*LbEndpoint) Descriptor() ([]byte, []int) {
	return file_config_endpoint_v1_endpoint_components_proto_rawDescGZIP(), []int{1}
}

func (x *LbEndpoint) GetHostIdentifier() isLbEndpoint_HostIdentifier {
	if x != nil {
		return x.HostIdentifier
	}
	return nil
}

func (x *LbEndpoint) GetEndpoint() *Endpoint {
	if x != nil {
		if x, ok := x.HostIdentifier.(*LbEndpoint_Endpoint); ok {
			return x.Endpoint
		}
	}
	return nil
}

func (x *LbEndpoint) GetEndpointName() string {
	if x != nil {
		if x, ok := x.HostIdentifier.(*LbEndpoint_EndpointName); ok {
			return x.EndpointName
		}
	}
	return ""
}

func (x *LbEndpoint) GetLoadBalancingWeight() *wrapperspb.UInt32Value {
	if x != nil {
		return x.LoadBalancingWeight
	}
	return nil
}

type isLbEndpoint_HostIdentifier interface {
	isLbEndpoint_HostIdentifier()
}

type LbEndpoint_Endpoint struct {
	Endpoint *Endpoint `protobuf:"bytes,1,opt,name=endpoint,proto3,oneof"`
}

type LbEndpoint_EndpointName struct {
	EndpointName string `protobuf:"bytes,5,opt,name=endpoint_name,json=endpointName,proto3,oneof"`
}

func (*LbEndpoint_Endpoint) isLbEndpoint_HostIdentifier() {}

func (*LbEndpoint_EndpointName) isLbEndpoint_HostIdentifier() {}

type LocalityLbEndpoints struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	LbEndpoints         []*LbEndpoint           `protobuf:"bytes,2,rep,name=lb_endpoints,json=lbEndpoints,proto3" json:"lb_endpoints,omitempty"`
	LoadBalancingWeight *wrapperspb.UInt32Value `protobuf:"bytes,3,opt,name=load_balancing_weight,json=loadBalancingWeight,proto3" json:"load_balancing_weight,omitempty"`
	Priority            uint32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Proximity           *wrapperspb.UInt32Value `protobuf:"bytes,6,opt,name=proximity,proto3" json:"proximity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LocalityLbEndpoints) Reset() {
	*x = LocalityLbEndpoints{}
	mi := &file_config_endpoint_v1_endpoint_components_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalityLbEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalityLbEndpoints) ProtoMessage() {}

func (x *LocalityLbEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_config_endpoint_v1_endpoint_components_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalityLbEndpoints.ProtoReflect.Descriptor instead.
func (*LocalityLbEndpoints) Descriptor() ([]byte, []int) {
	return file_config_endpoint_v1_endpoint_components_proto_rawDescGZIP(), []int{2}
}

func (x *LocalityLbEndpoints) GetLbEndpoints() []*LbEndpoint {
	if x != nil {
		return x.LbEndpoints
	}
	return nil
}

func (x *LocalityLbEndpoints) GetLoadBalancingWeight() *wrapperspb.UInt32Value {
	if x != nil {
		return x.LoadBalancingWeight
	}
	return nil
}

func (x *LocalityLbEndpoints) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *LocalityLbEndpoints) GetProximity() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Proximity
	}
	return nil
}

type LocalityLbEndpoints_LbEndpointList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LbEndpoints   []*LbEndpoint          `protobuf:"bytes,1,rep,name=lb_endpoints,json=lbEndpoints,proto3" json:"lb_endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalityLbEndpoints_LbEndpointList) Reset() {
	*x = LocalityLbEndpoints_LbEndpointList{}
	mi := &file_config_endpoint_v1_endpoint_components_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalityLbEndpoints_LbEndpointList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalityLbEndpoints_LbEndpointList) ProtoMessage() {}

func (x *LocalityLbEndpoints_LbEndpointList) ProtoReflect() protoreflect.Message {
	mi := &file_config_endpoint_v1_endpoint_components_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalityLbEndpoints_LbEndpointList.ProtoReflect.Descriptor instead.
func (*LocalityLbEndpoints_LbEndpointList) Descriptor() ([]byte, []int) {
	return file_config_endpoint_v1_endpoint_components_proto_rawDescGZIP(), []int{2, 0}
}

func (x *LocalityLbEndpoints_LbEndpointList) GetLbEndpoints() []*LbEndpoint {
	if x != nil {
		return x.LbEndpoints
	}
	return nil
}

var File_config_endpoint_v1_endpoint_components_proto protoreflect.FileDescriptor

const file_config_endpoint_v1_endpoint_components_proto_rawDesc = "" +
	"\n" +
	",config/endpoint/v1/endpoint_components.proto\x12\x12config.endpoint.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\n" +
	"\n" +
	"\bEndpoint\"\xd4\x01\n" +
	"\n" +
	"LbEndpoint\x12:\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1c.config.endpoint.v1.EndpointH\x00R\bendpoint\x12%\n" +
	"\rendpoint_name\x18\x05 \x01(\tH\x00R\fendpointName\x12P\n" +
	"\x15load_balancing_weight\x18\x04 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x13loadBalancingWeightB\x11\n" +
	"\x0fhost_identifier\"\xd7\x02\n" +
	"\x13LocalityLbEndpoints\x12A\n" +
	"\flb_endpoints\x18\x02 \x03(\v2\x1e.config.endpoint.v1.LbEndpointR\vlbEndpoints\x12P\n" +
	"\x15load_balancing_weight\x18\x03 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x13loadBalancingWeight\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\x12:\n" +
	"\tproximity\x18\x06 \x01(\v2\x1c.google.protobuf.UInt32ValueR\tproximity\x1aS\n" +
	"\x0eLbEndpointList\x12A\n" +
	"\flb_endpoints\x18\x01 \x03(\v2\x1e.config.endpoint.v1.LbEndpointR\vlbEndpointsBCZAgithub.com/dubbo-kubernetes/xds-api/config/endpoint/v1;endpointv1b\x06proto3"

var (
	file_config_endpoint_v1_endpoint_components_proto_rawDescOnce sync.Once
	file_config_endpoint_v1_endpoint_components_proto_rawDescData []byte
)

func file_config_endpoint_v1_endpoint_components_proto_rawDescGZIP() []byte {
	file_config_endpoint_v1_endpoint_components_proto_rawDescOnce.Do(func() {
		file_config_endpoint_v1_endpoint_components_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_endpoint_v1_endpoint_components_proto_rawDesc), len(file_config_endpoint_v1_endpoint_components_proto_rawDesc)))
	})
	return file_config_endpoint_v1_endpoint_components_proto_rawDescData
}

var file_config_endpoint_v1_endpoint_components_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_config_endpoint_v1_endpoint_components_proto_goTypes = []any{
	(*Endpoint)(nil),                           // 0: config.endpoint.v1.Endpoint
	(*LbEndpoint)(nil),                         // 1: config.endpoint.v1.LbEndpoint
	(*LocalityLbEndpoints)(nil),                // 2: config.endpoint.v1.LocalityLbEndpoints
	(*LocalityLbEndpoints_LbEndpointList)(nil), // 3: config.endpoint.v1.LocalityLbEndpoints.LbEndpointList
	(*wrapperspb.UInt32Value)(nil),             // 4: google.protobuf.UInt32Value
}
var file_config_endpoint_v1_endpoint_components_proto_depIdxs = []int32{
	0, // 0: config.endpoint.v1.LbEndpoint.endpoint:type_name -> config.endpoint.v1.Endpoint
	4, // 1: config.endpoint.v1.LbEndpoint.load_balancing_weight:type_name -> google.protobuf.UInt32Value
	1, // 2: config.endpoint.v1.LocalityLbEndpoints.lb_endpoints:type_name -> config.endpoint.v1.LbEndpoint
	4, // 3: config.endpoint.v1.LocalityLbEndpoints.load_balancing_weight:type_name -> google.protobuf.UInt32Value
	4, // 4: config.endpoint.v1.LocalityLbEndpoints.proximity:type_name -> google.protobuf.UInt32Value
	1, // 5: config.endpoint.v1.LocalityLbEndpoints.LbEndpointList.lb_endpoints:type_name -> config.endpoint.v1.LbEndpoint
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_config_endpoint_v1_endpoint_components_proto_init() }
func file_config_endpoint_v1_endpoint_components_proto_init() {
	if File_config_endpoint_v1_endpoint_components_proto != nil {
		return
	}
	file_config_endpoint_v1_endpoint_components_proto_msgTypes[1].OneofWrappers = []any{
		(*LbEndpoint_Endpoint)(nil),
		(*LbEndpoint_EndpointName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_endpoint_v1_endpoint_components_proto_rawDesc), len(file_config_endpoint_v1_endpoint_components_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_endpoint_v1_endpoint_components_proto_goTypes,
		DependencyIndexes: file_config_endpoint_v1_endpoint_components_proto_depIdxs,
		MessageInfos:      file_config_endpoint_v1_endpoint_components_proto_msgTypes,
	}.Build()
	File_config_endpoint_v1_endpoint_components_proto = out.File
	file_config_endpoint_v1_endpoint_components_proto_goTypes = nil
	file_config_endpoint_v1_endpoint_components_proto_depIdxs = nil
}
