// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: config/listener/v1/listener.proto

package listenerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The additional address the listener is listening on.
type AdditionalAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdditionalAddress) Reset() {
	*x = AdditionalAddress{}
	mi := &file_config_listener_v1_listener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalAddress) ProtoMessage() {}

func (x *AdditionalAddress) ProtoReflect() protoreflect.Message {
	mi := &file_config_listener_v1_listener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalAddress.ProtoReflect.Descriptor instead.
func (*AdditionalAddress) Descriptor() ([]byte, []int) {
	return file_config_listener_v1_listener_proto_rawDescGZIP(), []int{0}
}

type Listener struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AdditionalAddresses []*AdditionalAddress   `protobuf:"bytes,33,rep,name=additional_addresses,json=additionalAddresses,proto3" json:"additional_addresses,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Listener) Reset() {
	*x = Listener{}
	mi := &file_config_listener_v1_listener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_config_listener_v1_listener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_config_listener_v1_listener_proto_rawDescGZIP(), []int{1}
}

func (x *Listener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listener) GetAdditionalAddresses() []*AdditionalAddress {
	if x != nil {
		return x.AdditionalAddresses
	}
	return nil
}

var File_config_listener_v1_listener_proto protoreflect.FileDescriptor

const file_config_listener_v1_listener_proto_rawDesc = "" +
	"\n" +
	"!config/listener/v1/listener.proto\x12\x12config.listener.v1\"\x13\n" +
	"\x11AdditionalAddress\"x\n" +
	"\bListener\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12X\n" +
	"\x14additional_addresses\x18! \x03(\v2%.config.listener.v1.AdditionalAddressR\x13additionalAddressesBCZAgithub.com/dubbo-kubernetes/xds-api/config/listener/v1;listenerv1b\x06proto3"

var (
	file_config_listener_v1_listener_proto_rawDescOnce sync.Once
	file_config_listener_v1_listener_proto_rawDescData []byte
)

func file_config_listener_v1_listener_proto_rawDescGZIP() []byte {
	file_config_listener_v1_listener_proto_rawDescOnce.Do(func() {
		file_config_listener_v1_listener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_listener_v1_listener_proto_rawDesc), len(file_config_listener_v1_listener_proto_rawDesc)))
	})
	return file_config_listener_v1_listener_proto_rawDescData
}

var file_config_listener_v1_listener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_listener_v1_listener_proto_goTypes = []any{
	(*AdditionalAddress)(nil), // 0: config.listener.v1.AdditionalAddress
	(*Listener)(nil),          // 1: config.listener.v1.Listener
}
var file_config_listener_v1_listener_proto_depIdxs = []int32{
	0, // 0: config.listener.v1.Listener.additional_addresses:type_name -> config.listener.v1.AdditionalAddress
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_listener_v1_listener_proto_init() }
func file_config_listener_v1_listener_proto_init() {
	if File_config_listener_v1_listener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_listener_v1_listener_proto_rawDesc), len(file_config_listener_v1_listener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_listener_v1_listener_proto_goTypes,
		DependencyIndexes: file_config_listener_v1_listener_proto_depIdxs,
		MessageInfos:      file_config_listener_v1_listener_proto_msgTypes,
	}.Build()
	File_config_listener_v1_listener_proto = out.File
	file_config_listener_v1_listener_proto_goTypes = nil
	file_config_listener_v1_listener_proto_depIdxs = nil
}
