// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: extensions/filters/v1/http/router/router.proto

package routerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Router struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Router) Reset() {
	*x = Router{}
	mi := &file_extensions_filters_v1_http_router_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Router) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Router) ProtoMessage() {}

func (x *Router) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_http_router_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Router.ProtoReflect.Descriptor instead.
func (*Router) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_router_router_proto_rawDescGZIP(), []int{0}
}

var File_extensions_filters_v1_http_router_router_proto protoreflect.FileDescriptor

const file_extensions_filters_v1_http_router_router_proto_rawDesc = "" +
	"\n" +
	".extensions/filters/v1/http/router/router.proto\x12!extensions.filters.http.router.v1\"\b\n" +
	"\x06RouterBPZNgithub.com/dubbo-kubernetes/xds-api/extensions/filters/http/router/v1;routerv1b\x06proto3"

var (
	file_extensions_filters_v1_http_router_router_proto_rawDescOnce sync.Once
	file_extensions_filters_v1_http_router_router_proto_rawDescData []byte
)

func file_extensions_filters_v1_http_router_router_proto_rawDescGZIP() []byte {
	file_extensions_filters_v1_http_router_router_proto_rawDescOnce.Do(func() {
		file_extensions_filters_v1_http_router_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_http_router_router_proto_rawDesc), len(file_extensions_filters_v1_http_router_router_proto_rawDesc)))
	})
	return file_extensions_filters_v1_http_router_router_proto_rawDescData
}

var file_extensions_filters_v1_http_router_router_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extensions_filters_v1_http_router_router_proto_goTypes = []any{
	(*Router)(nil), // 0: extensions.filters.http.router.v1.Router
}
var file_extensions_filters_v1_http_router_router_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extensions_filters_v1_http_router_router_proto_init() }
func file_extensions_filters_v1_http_router_router_proto_init() {
	if File_extensions_filters_v1_http_router_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_http_router_router_proto_rawDesc), len(file_extensions_filters_v1_http_router_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_filters_v1_http_router_router_proto_goTypes,
		DependencyIndexes: file_extensions_filters_v1_http_router_router_proto_depIdxs,
		MessageInfos:      file_extensions_filters_v1_http_router_router_proto_msgTypes,
	}.Build()
	File_extensions_filters_v1_http_router_router_proto = out.File
	file_extensions_filters_v1_http_router_router_proto_goTypes = nil
	file_extensions_filters_v1_http_router_router_proto_depIdxs = nil
}
