// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: config/core/v1/base.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiConfigSource_ApiType int32

const (
	ApiConfigSource_REST       ApiConfigSource_ApiType = 0
	ApiConfigSource_GRPC       ApiConfigSource_ApiType = 1
	ApiConfigSource_DELTA_GRPC ApiConfigSource_ApiType = 2
)

// Enum value maps for ApiConfigSource_ApiType.
var (
	ApiConfigSource_ApiType_name = map[int32]string{
		0: "REST",
		1: "GRPC",
		2: "DELTA_GRPC",
	}
	ApiConfigSource_ApiType_value = map[string]int32{
		"REST":       0,
		"GRPC":       1,
		"DELTA_GRPC": 2,
	}
)

func (x ApiConfigSource_ApiType) Enum() *ApiConfigSource_ApiType {
	p := new(ApiConfigSource_ApiType)
	*p = x
	return p
}

func (x ApiConfigSource_ApiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiConfigSource_ApiType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_core_v1_base_proto_enumTypes[0].Descriptor()
}

func (ApiConfigSource_ApiType) Type() protoreflect.EnumType {
	return &file_config_core_v1_base_proto_enumTypes[0]
}

func (x ApiConfigSource_ApiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiConfigSource_ApiType.Descriptor instead.
func (ApiConfigSource_ApiType) EnumDescriptor() ([]byte, []int) {
	return file_config_core_v1_base_proto_rawDescGZIP(), []int{5, 0}
}

// Identifies location of where either Envoy runs or where upstream hosts run.
type Locality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locality) Reset() {
	*x = Locality{}
	mi := &file_config_core_v1_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locality) ProtoMessage() {}

func (x *Locality) ProtoReflect() protoreflect.Message {
	mi := &file_config_core_v1_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locality.ProtoReflect.Descriptor instead.
func (*Locality) Descriptor() ([]byte, []int) {
	return file_config_core_v1_base_proto_rawDescGZIP(), []int{0}
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Locality      *Locality              `protobuf:"bytes,4,opt,name=locality,proto3" json:"locality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_config_core_v1_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_config_core_v1_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_config_core_v1_base_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Node) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Node) GetLocality() *Locality {
	if x != nil {
		return x.Locality
	}
	return nil
}

type TransportSocket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ConfigType:
	//
	//	*TransportSocket_TypedConfig
	ConfigType    isTransportSocket_ConfigType `protobuf_oneof:"config_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportSocket) Reset() {
	*x = TransportSocket{}
	mi := &file_config_core_v1_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportSocket) ProtoMessage() {}

func (x *TransportSocket) ProtoReflect() protoreflect.Message {
	mi := &file_config_core_v1_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportSocket.ProtoReflect.Descriptor instead.
func (*TransportSocket) Descriptor() ([]byte, []int) {
	return file_config_core_v1_base_proto_rawDescGZIP(), []int{2}
}

func (x *TransportSocket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransportSocket) GetConfigType() isTransportSocket_ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return nil
}

func (x *TransportSocket) GetTypedConfig() *anypb.Any {
	if x != nil {
		if x, ok := x.ConfigType.(*TransportSocket_TypedConfig); ok {
			return x.TypedConfig
		}
	}
	return nil
}

type isTransportSocket_ConfigType interface {
	isTransportSocket_ConfigType()
}

type TransportSocket_TypedConfig struct {
	TypedConfig *anypb.Any `protobuf:"bytes,3,opt,name=typed_config,json=typedConfig,proto3,oneof"`
}

func (*TransportSocket_TypedConfig) isTransportSocket_ConfigType() {}

type ControlPlane struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlane) Reset() {
	*x = ControlPlane{}
	mi := &file_config_core_v1_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlane) ProtoMessage() {}

func (x *ControlPlane) ProtoReflect() protoreflect.Message {
	mi := &file_config_core_v1_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlane.ProtoReflect.Descriptor instead.
func (*ControlPlane) Descriptor() ([]byte, []int) {
	return file_config_core_v1_base_proto_rawDescGZIP(), []int{3}
}

func (x *ControlPlane) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

// Configuration source for xDS APIs
type ConfigSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ConfigSourceSpecifier:
	//
	//	*ConfigSource_ApiConfigSource
	ConfigSourceSpecifier isConfigSource_ConfigSourceSpecifier `protobuf_oneof:"config_source_specifier"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConfigSource) Reset() {
	*x = ConfigSource{}
	mi := &file_config_core_v1_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSource) ProtoMessage() {}

func (x *ConfigSource) ProtoReflect() protoreflect.Message {
	mi := &file_config_core_v1_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSource.ProtoReflect.Descriptor instead.
func (*ConfigSource) Descriptor() ([]byte, []int) {
	return file_config_core_v1_base_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigSource) GetConfigSourceSpecifier() isConfigSource_ConfigSourceSpecifier {
	if x != nil {
		return x.ConfigSourceSpecifier
	}
	return nil
}

func (x *ConfigSource) GetApiConfigSource() *ApiConfigSource {
	if x != nil {
		if x, ok := x.ConfigSourceSpecifier.(*ConfigSource_ApiConfigSource); ok {
			return x.ApiConfigSource
		}
	}
	return nil
}

type isConfigSource_ConfigSourceSpecifier interface {
	isConfigSource_ConfigSourceSpecifier()
}

type ConfigSource_ApiConfigSource struct {
	ApiConfigSource *ApiConfigSource `protobuf:"bytes,2,opt,name=api_config_source,json=apiConfigSource,proto3,oneof"`
}

func (*ConfigSource_ApiConfigSource) isConfigSource_ConfigSourceSpecifier() {}

type ApiConfigSource struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ApiType       ApiConfigSource_ApiType `protobuf:"varint,1,opt,name=api_type,json=apiType,proto3,enum=config.core.v1.ApiConfigSource_ApiType" json:"api_type,omitempty"`
	GrpcServices  []string                `protobuf:"bytes,2,rep,name=grpc_services,json=grpcServices,proto3" json:"grpc_services,omitempty"`
	RefreshDelay  *durationpb.Duration    `protobuf:"bytes,3,opt,name=refresh_delay,json=refreshDelay,proto3" json:"refresh_delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiConfigSource) Reset() {
	*x = ApiConfigSource{}
	mi := &file_config_core_v1_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiConfigSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiConfigSource) ProtoMessage() {}

func (x *ApiConfigSource) ProtoReflect() protoreflect.Message {
	mi := &file_config_core_v1_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiConfigSource.ProtoReflect.Descriptor instead.
func (*ApiConfigSource) Descriptor() ([]byte, []int) {
	return file_config_core_v1_base_proto_rawDescGZIP(), []int{5}
}

func (x *ApiConfigSource) GetApiType() ApiConfigSource_ApiType {
	if x != nil {
		return x.ApiType
	}
	return ApiConfigSource_REST
}

func (x *ApiConfigSource) GetGrpcServices() []string {
	if x != nil {
		return x.GrpcServices
	}
	return nil
}

func (x *ApiConfigSource) GetRefreshDelay() *durationpb.Duration {
	if x != nil {
		return x.RefreshDelay
	}
	return nil
}

var File_config_core_v1_base_proto protoreflect.FileDescriptor

const file_config_core_v1_base_proto_rawDesc = "" +
	"\n" +
	"\x19config/core/v1/base.proto\x12\x0econfig.core.v1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1egoogle/protobuf/duration.proto\"\n" +
	"\n" +
	"\bLocality\"\x9b\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x124\n" +
	"\blocality\x18\x04 \x01(\v2\x18.config.core.v1.LocalityR\blocality\"o\n" +
	"\x0fTransportSocket\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\ftyped_config\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\vtypedConfigB\r\n" +
	"\vconfig_type\".\n" +
	"\fControlPlane\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"x\n" +
	"\fConfigSource\x12M\n" +
	"\x11api_config_source\x18\x02 \x01(\v2\x1f.config.core.v1.ApiConfigSourceH\x00R\x0fapiConfigSourceB\x19\n" +
	"\x17config_source_specifier\"\xe9\x01\n" +
	"\x0fApiConfigSource\x12B\n" +
	"\bapi_type\x18\x01 \x01(\x0e2'.config.core.v1.ApiConfigSource.ApiTypeR\aapiType\x12#\n" +
	"\rgrpc_services\x18\x02 \x03(\tR\fgrpcServices\x12>\n" +
	"\rrefresh_delay\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\frefreshDelay\"-\n" +
	"\aApiType\x12\b\n" +
	"\x04REST\x10\x00\x12\b\n" +
	"\x04GRPC\x10\x01\x12\x0e\n" +
	"\n" +
	"DELTA_GRPC\x10\x02B;Z9github.com/dubbo-kubernetes/xds-api/config/core/v1;corev1b\x06proto3"

var (
	file_config_core_v1_base_proto_rawDescOnce sync.Once
	file_config_core_v1_base_proto_rawDescData []byte
)

func file_config_core_v1_base_proto_rawDescGZIP() []byte {
	file_config_core_v1_base_proto_rawDescOnce.Do(func() {
		file_config_core_v1_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_core_v1_base_proto_rawDesc), len(file_config_core_v1_base_proto_rawDesc)))
	})
	return file_config_core_v1_base_proto_rawDescData
}

var file_config_core_v1_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_core_v1_base_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_config_core_v1_base_proto_goTypes = []any{
	(ApiConfigSource_ApiType)(0), // 0: config.core.v1.ApiConfigSource.ApiType
	(*Locality)(nil),             // 1: config.core.v1.Locality
	(*Node)(nil),                 // 2: config.core.v1.Node
	(*TransportSocket)(nil),      // 3: config.core.v1.TransportSocket
	(*ControlPlane)(nil),         // 4: config.core.v1.ControlPlane
	(*ConfigSource)(nil),         // 5: config.core.v1.ConfigSource
	(*ApiConfigSource)(nil),      // 6: config.core.v1.ApiConfigSource
	(*structpb.Struct)(nil),      // 7: google.protobuf.Struct
	(*anypb.Any)(nil),            // 8: google.protobuf.Any
	(*durationpb.Duration)(nil),  // 9: google.protobuf.Duration
}
var file_config_core_v1_base_proto_depIdxs = []int32{
	7, // 0: config.core.v1.Node.metadata:type_name -> google.protobuf.Struct
	1, // 1: config.core.v1.Node.locality:type_name -> config.core.v1.Locality
	8, // 2: config.core.v1.TransportSocket.typed_config:type_name -> google.protobuf.Any
	6, // 3: config.core.v1.ConfigSource.api_config_source:type_name -> config.core.v1.ApiConfigSource
	0, // 4: config.core.v1.ApiConfigSource.api_type:type_name -> config.core.v1.ApiConfigSource.ApiType
	9, // 5: config.core.v1.ApiConfigSource.refresh_delay:type_name -> google.protobuf.Duration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_config_core_v1_base_proto_init() }
func file_config_core_v1_base_proto_init() {
	if File_config_core_v1_base_proto != nil {
		return
	}
	file_config_core_v1_base_proto_msgTypes[2].OneofWrappers = []any{
		(*TransportSocket_TypedConfig)(nil),
	}
	file_config_core_v1_base_proto_msgTypes[4].OneofWrappers = []any{
		(*ConfigSource_ApiConfigSource)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_core_v1_base_proto_rawDesc), len(file_config_core_v1_base_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_core_v1_base_proto_goTypes,
		DependencyIndexes: file_config_core_v1_base_proto_depIdxs,
		EnumInfos:         file_config_core_v1_base_proto_enumTypes,
		MessageInfos:      file_config_core_v1_base_proto_msgTypes,
	}.Build()
	File_config_core_v1_base_proto = out.File
	file_config_core_v1_base_proto_goTypes = nil
	file_config_core_v1_base_proto_depIdxs = nil
}
