// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: route/v1/route.proto

package routev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VirtualHosts  []*VirtualHost         `protobuf:"bytes,2,rep,name=virtual_hosts,json=virtualHosts,proto3" json:"virtual_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteConfiguration) Reset() {
	*x = RouteConfiguration{}
	mi := &file_route_v1_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfiguration) ProtoMessage() {}

func (x *RouteConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfiguration.ProtoReflect.Descriptor instead.
func (*RouteConfiguration) Descriptor() ([]byte, []int) {
	return file_route_v1_route_proto_rawDescGZIP(), []int{0}
}

func (x *RouteConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RouteConfiguration) GetVirtualHosts() []*VirtualHost {
	if x != nil {
		return x.VirtualHosts
	}
	return nil
}

var File_route_v1_route_proto protoreflect.FileDescriptor

const file_route_v1_route_proto_rawDesc = "" +
	"\n" +
	"\x14route/v1/route.proto\x12\broute.v1\x1a\x1froute/v1/route_components.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/wrappers.proto\"d\n" +
	"\x12RouteConfiguration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\rvirtual_hosts\x18\x02 \x03(\v2\x15.route.v1.VirtualHostR\fvirtualHostsB6Z4github.com/dubbo-kubernetes/xds-api/route/v1;routev1b\x06proto3"

var (
	file_route_v1_route_proto_rawDescOnce sync.Once
	file_route_v1_route_proto_rawDescData []byte
)

func file_route_v1_route_proto_rawDescGZIP() []byte {
	file_route_v1_route_proto_rawDescOnce.Do(func() {
		file_route_v1_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_route_v1_route_proto_rawDesc), len(file_route_v1_route_proto_rawDesc)))
	})
	return file_route_v1_route_proto_rawDescData
}

var file_route_v1_route_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_route_v1_route_proto_goTypes = []any{
	(*RouteConfiguration)(nil), // 0: route.v1.RouteConfiguration
	(*VirtualHost)(nil),        // 1: route.v1.VirtualHost
}
var file_route_v1_route_proto_depIdxs = []int32{
	1, // 0: route.v1.RouteConfiguration.virtual_hosts:type_name -> route.v1.VirtualHost
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_route_v1_route_proto_init() }
func file_route_v1_route_proto_init() {
	if File_route_v1_route_proto != nil {
		return
	}
	file_route_v1_route_components_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_route_v1_route_proto_rawDesc), len(file_route_v1_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_route_v1_route_proto_goTypes,
		DependencyIndexes: file_route_v1_route_proto_depIdxs,
		MessageInfos:      file_route_v1_route_proto_msgTypes,
	}.Build()
	File_route_v1_route_proto = out.File
	file_route_v1_route_proto_goTypes = nil
	file_route_v1_route_proto_depIdxs = nil
}
