// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: service/secret/v1/sds.proto

package secretv1

import (
	v1 "github.com/dubbo-kubernetes/xds-api/service/discovery/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_secret_v1_sds_proto protoreflect.FileDescriptor

const file_service_secret_v1_sds_proto_rawDesc = "" +
	"\n" +
	"\x1bservice/secret/v1/sds.proto\x12\x11service.secret.v1\x1a$service/discovery/v1/discovery.proto2\xd0\x02\n" +
	"\x16SecretDiscoveryService\x12m\n" +
	"\fDeltaSecrets\x12+.service.discovery.v1.DeltaDiscoveryRequest\x1a,.service.discovery.v1.DeltaDiscoveryResponse(\x010\x01\x12d\n" +
	"\rStreamSecrets\x12&.service.discovery.v1.DiscoveryRequest\x1a'.service.discovery.v1.DiscoveryResponse(\x010\x01\x12a\n" +
	"\fFetchSecrets\x12&.service.discovery.v1.DiscoveryRequest\x1a'.service.discovery.v1.DiscoveryResponse\"\x00B@Z>github.com/dubbo-kubernetes/xds-api/service/secret/v1;secretv1b\x06proto3"

var file_service_secret_v1_sds_proto_goTypes = []any{
	(*v1.DeltaDiscoveryRequest)(nil),  // 0: service.discovery.v1.DeltaDiscoveryRequest
	(*v1.DiscoveryRequest)(nil),       // 1: service.discovery.v1.DiscoveryRequest
	(*v1.DeltaDiscoveryResponse)(nil), // 2: service.discovery.v1.DeltaDiscoveryResponse
	(*v1.DiscoveryResponse)(nil),      // 3: service.discovery.v1.DiscoveryResponse
}
var file_service_secret_v1_sds_proto_depIdxs = []int32{
	0, // 0: service.secret.v1.SecretDiscoveryService.DeltaSecrets:input_type -> service.discovery.v1.DeltaDiscoveryRequest
	1, // 1: service.secret.v1.SecretDiscoveryService.StreamSecrets:input_type -> service.discovery.v1.DiscoveryRequest
	1, // 2: service.secret.v1.SecretDiscoveryService.FetchSecrets:input_type -> service.discovery.v1.DiscoveryRequest
	2, // 3: service.secret.v1.SecretDiscoveryService.DeltaSecrets:output_type -> service.discovery.v1.DeltaDiscoveryResponse
	3, // 4: service.secret.v1.SecretDiscoveryService.StreamSecrets:output_type -> service.discovery.v1.DiscoveryResponse
	3, // 5: service.secret.v1.SecretDiscoveryService.FetchSecrets:output_type -> service.discovery.v1.DiscoveryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_secret_v1_sds_proto_init() }
func file_service_secret_v1_sds_proto_init() {
	if File_service_secret_v1_sds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_secret_v1_sds_proto_rawDesc), len(file_service_secret_v1_sds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_secret_v1_sds_proto_goTypes,
		DependencyIndexes: file_service_secret_v1_sds_proto_depIdxs,
	}.Build()
	File_service_secret_v1_sds_proto = out.File
	file_service_secret_v1_sds_proto_goTypes = nil
	file_service_secret_v1_sds_proto_depIdxs = nil
}
